### ISSUE TITLE
[Feature Request] Reactive System

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [Doraku/DefaultEcs#101]
Hi guys,
do you plan to implement a reactive system? Something that updates changed components only, like imagine 1000 monsters and only three change their position and I want to update only components or entities that depend on this information.

Cheers,
Georg

**Comment by Doraku** [comment]
Hey, this is actually already possible, to create reactive EntitySet/EntityMap/EntitiesMap, you only have to state so when building your rules with all the `When...` methods:
```csharp
EntitySet set = world.GetEntities().WhenChanged<Position>().AsSet();
```
The real specificity of those react collection is that you have to call the `Complete()` method once your are done processing its content so it can be cleared. This is already done for you in all implementation of `ISystem` which take those collections (`AEntitySystem`, `AEntityBufferedSystem`, `AEntitiesSystem`) and you can also use the attribute declaration to auto create the rules
```csharp
[WhenChanged(typeof(Position)]
[With(typeof(SomeOtherComponent))]
public sealed class PositionSystem : AEntitySystem<float>
{
    public PositionSystem(World world, IParallelRunner runner)
        : base(world, runner)
    {
    }

    protected override void Update(float elaspedTime, in Entity entity)
    {
        ...
    }
}
```
Something important to keep in mind when working with reactive system is that for your component update to be catched by the framework, you HAVE to use [Entity.Set](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/DefaultEcs-Entity-Set-T-(T).md) or [Entity.NotifyChanged](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/DefaultEcs-Entity-NotifyChanged-T-().md), you can just do `entity.Get<Position>().X = 42;` and expect it to work ^^".

Feel free to ask if you have other questions.

**Comment by georg-eckert-zeiss** [comment]
Tahts great news : ) I thougt that means, the system reacts if a whole `Position` component is changed - but not just a value of it. Thanks for clearing the matter : )

**Comment by Doraku** [comment]
ouch see my edit:
>you can't just do entity.Get<Position>().X = 42; and expect it to work ^^".
can't, if there was one typo I shouldn't have done it's this one!

**Comment by georg-eckert-zeiss** [comment]
Ah - yeah. Was already wondering if that's on purpose :D. Is there a way to have that for specific values?

**Comment by Doraku** [comment]
> Ah - yeah. Was already wondering if that's on purpose :D. Is there a way to have that for specific values? Like knowing in the update method, which value has been changed?

if you mean which field/property of the component has changed, no. It would need to be handled by the component itself if you need this knowledge :/

For you system example, you would only get entity which BOTH the Camera and Transform component have changed. If you want an either rule you need to use the `WhenEitherChanged` attribute/method instead. Also you probably want to add `WhenAdded` rule so you also process your entity the first time you add your component.

**Comment by georg-eckert-zeiss** [comment]
Alright, thank you : )

**Comment by Doraku** [comment]
sorry sorry see my edit >_>

**Comment by georg-eckert-zeiss** [comment]
No worries ;)
