### ISSUE TITLE
Maybe usefull functions?

### ISSUE THREAD

**Issue by PodeCaradox** [Doraku/DefaultEcs#107]
Hey @Doraku,

i just added some extension to the World class and thoght maybe others find them usefull two.
```
    public static class WorldExtension
    {
        public static Entity GetEntity<T>(this World world)
        {
            return world.GetEntities().With<T>().AsSet().GetEntities()[0];
        }

        public static ref T GetComponentFromFirstEntity<T>(this World world)
        {
            return ref world.GetEntities().With<T>().AsSet().GetEntities()[0].Get<T>();
        }

        public static Entity[] GetEntitiesByComponent<T>(this World world)
        {
            return world.GetEntities().With<T>().AsSet().GetEntities().ToArray();
        }
    }
```

I use them because sometimes i only have one Entity with a certain component for example:
Camera, GameConfig, ShowOffset, Editor, brush, etc.

This help me for more readability in the Constructor.
`   _editor = world.GetEntity<Editor>();`
instead of
`_editor = world.GetEntities().With<Editor>().AsSet().GetEntities()[0];`

And yeah shouldnt be used in a Update Method only in Constructor or one time usage

**Comment by Doraku** [comment]
Hey, you should prefer [AsEnumerable](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/DefaultEcs-EntityRuleBuilder-AsEnumerable().md) (added in the last version) to AsSet, else the EntitySet will stay in memory and keep receiving events of entity/component modifications :) I think I actually added this api specifically after looking at your code jam repo and seeing this usage haha
You can also directly get components from the world with [World.Get](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/DefaultEcs-World-Get-T-().md) without using entities if you know you only have one.

**Comment by PodeCaradox** [comment]
ah yeah I just updated it haha xD
if I get components with world.get ,do I get it as Referenz?
or what is the best way with entity's which I need in my update too(for example camera, specially property's) , get the references in the constructor or load them with get in the update? (also importent parralel update will load them then x times?, can I maybe load them on preupdate and just send them as parameter to the update method?)

also what is faster make an array of entity's(constructor) where I need a specific component for my update or use the world.getComponents<t> an use this in the update?

**Comment by Doraku** [comment]
> if I get components with world.get ,do I get it as Referenz?

Yes it returns a Span of the component so you can edit them.

> or what is the best way with entity's which I need in my update too(for example camera, specially property's) , get the references in the constructor or load them with get in the update? (also importent parralel update will load them then x times?, can I maybe load them on preupdate and just send them as parameter to the update method?)

Depends, if it never ever change (like only one entity with a camera) you can retrieve it in the constructor, but just in case I like to create an EntitySet (or Map or Multimap depending of my need) in the constructor that way it is automatically maintained and ready to use for minimal cost in the hot path Update. Getting them in the Update override will do the operation n times for n threads indeed, while the PreUpdate and PostUpdate will occur in a single thread.

> also what is faster make an array of entity's(constructor) where I need a specific component for my update or use the world.getComponents an use this in the update?

The code used by entity to get components is actually almost the same as the one `World.Get` uses, it's just that you don't know the entity referencing it but performance wise it should be pretty close.

**Comment by PodeCaradox** [comment]
Why im not using the EntitySet is because i use Methods that get used more often in static classes like Unity do with there ECS(new math class), so i can have a much cleaner look(not so big Systems, i like to keep them small) and easier editing if i have errors, and also reusable Code. Or do you have a better way to do such things like that? Im still learning best practice in ECS x).
For Example i have a following static class which i can use everywhere and get initialized after all Entitys are created.
```
  internal static class PosTransformer
    {
        private static Entity _map;
        private static Entity _gameConfig;
        private static Entity _miniMap;
        private static Entity _camera;
        internal static void Init(World world)
        {
            _map = world.GetEntity<Map>();
            _gameConfig = world.GetEntity<GameConfig>();
            _miniMap = world.GetEntity<Minimap>();
            _camera = world.GetEntity<Camera>();
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static Vector2 MouseToScreenPos(Point mousePosition)
        {
            Vector2 worldPosition = Vector2.Transform(new Vector2(mousePosition.X, mousePosition.Y), Matrix.Invert(_camera.Get<Camera>().Transform));
            return new Vector2((int)worldPosition.X, (int)worldPosition.Y);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static Point ScreenToWorldPos(Vector2 position)
        {
            ref var tileSize = ref _gameConfig.Get<GameConfig>().TileSize;
          
            
            float x = (position.Y / tileSize.Y) + (position.X / tileSize.X);
            float y = (position.Y / tileSize.Y) - (position.X / tileSize.X);
            //is needed because switching to minus coordinates and the float get almost to 1 but no quite and int cut it off :(
            if (x < 0)
                x -= 1;
            if (y < 0)
                y -= 1;
            Point point = new Point((int)x, (int)y);
            return point;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static Point ScreenToWorldPos(Point position)
        {
            ref var tileSize = ref _gameConfig.Get<GameConfig>().TileSize;

            Point point = Point.Zero;
            point.X = (int)((position.Y / tileSize.Y) + (position.X / tileSize.X));
            point.Y = (int)((position.Y / tileSize.Y) - (position.X / tileSize.X));
            return point;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static Vector2 MapToScreenPos(Point position)
        {

      
            ref var tileSize = ref _gameConfig.Get<GameConfig>().TileSizeHalf;


            int startPositionX = (int)(tileSize.X * position.X - tileSize.X * position.Y);
            int startPositionY = (int)(tileSize.Y * position.X + tileSize.Y * position.Y + tileSize.Y);
            var pos = new Vector2(startPositionX, startPositionY) ;

            return pos;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static Vector2 MapToScreenPos(Vector2 position)
        {
            ref var tileSize = ref _gameConfig.Get<GameConfig>().TileSizeHalf;
            //                                                          first x value                               than add y value
            float startPositionX = (tileSize.X * position.X - tileSize.X * position.Y);
            float startPositionY = (tileSize.Y * position.X + tileSize.Y * position.Y + tileSize.Y);
            var pos = new Vector2(startPositionX, startPositionY);
      
            return pos;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]

        internal static Point ScreenToChunkPos(Point position)
        {
            ref var tileSize = ref _gameConfig.Get<GameConfig>().TileSize;
            ref var chunkSize = ref _gameConfig.Get<GameConfig>().ChunkSize;
            Point point = Point.Zero;
            float y = (position.Y / tileSize.Y);
            float x = (position.X / tileSize.X);
            point.X = (int)(y + x) / chunkSize;
            point.Y = (int)(y - x) / chunkSize;

            return point;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static int MapToChunkKey(Point position)
        {
            ref var chunkSizeMap = ref _map.Get<Map>().ChunkSize;
            ref var chunkSize = ref _gameConfig.Get<GameConfig>().ChunkSize;
            float keyX = position.X / (float)chunkSize;
            if (keyX >= chunkSizeMap.X || keyX < 0) return -1;
            float keyY = position.Y / (float)chunkSize;
            if (keyY >= chunkSizeMap.Y || keyY < 0) return -1;
            return (int)keyX + (int)keyY * chunkSizeMap.X;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static Point MapToMinimapPos(float x, float y)
        {
            ref var miniMap = ref _miniMap.Get<Minimap>();
            return new Point((int)((x - y) * miniMap.minimap_tile_width * 0.5f + miniMap.x_offset), (int)((x + y) * miniMap.minimap_tile_height * 0.5f));
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static Vector2 MinimapToWorldPos(float x, float y)
        {
            ref var miniMap = ref _miniMap.Get<Minimap>();
            return new Vector2(x / miniMap.aspect_ratio_x, y / miniMap.aspect_ratio_y);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static Point MapToMinimapPos(Vector2 pos)
        {
            ref var miniMap = ref _miniMap.Get<Minimap>();
            return new Point((int)((pos.X - pos.Y) * miniMap.minimap_tile_width * 0.5f + miniMap.x_offset), (int)((pos.X + pos.Y) * miniMap.minimap_tile_height * 0.5f));
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static float PositionToDepth(Vector2 pos,int chunkKey,int tileKey)
        {
            ref var mapSizeInPixel = ref _map.Get<Map>().MapSizeInPixel;
            //todo
            return _map.Get<Map>().Chunks[chunkKey].Get<Chunk>().Tiles[tileKey].Get<DrawingInstance>().World.Z - (1 - pos.Y / mapSizeInPixel.Y) / mapSizeInPixel.Y - (1 - pos.X / mapSizeInPixel.X) / (mapSizeInPixel.X * mapSizeInPixel.X);//
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static int MapToTileKey(Point point)
        {
            ref var chunkSize = ref _gameConfig.Get<GameConfig>().ChunkSize;
            return point.X % chunkSize + point.Y % chunkSize * chunkSize;
        }
    }
```

and yeah changed my
```
 public static Entity GetEntity<T>(this World world)
        {
            return world.GetEntities().With<T>().AsEnumerable().First();
        }
```

**Comment by Doraku** [comment]
Personally I try not to rely on static types with states in case I need to use it in multiple contexts at the same times, I can preload a different scene with its own world and switch the active scene in my engine.

Do you actually use Map, GameConfig, Minimap and Camera as component in other systems/entities or just in your PosTransformer? Keep in mind that I am no ECS expert but to me it is really good a composition but it doesn't really make sens for singleton. I would either pass the instances needed for systems in their constructor or inside a custom state passed to the Update method of systems and move your converter methods into their related type or as extension  methods.

```csharp
public class MySystem : AEntitySetSystem<float>
{
    private readonly Map _map;
    private readonly Camera _camera;

    public MySystem(World world, Map map, Camera camera)
        base(world.GetEntities().With...)
    {
        _map = map;
        _camera = camera;
    }

    protected override void Update(float state, in Entity entity)
    {
        _map.ToChunkKey(entity.Get<Point>());
        ...
    }
}

// or

public class State
{
    public readonly float ElapsedTime;
    public readonly Map Map;
    public readonly Camera Camera;

    ...
}

public class MySystem : AEntitySetSystem<State>
{

    public MySystem(World world)
        base(world.GetEntities().With...)
    { }

    protected override void Update(State state, in Entity entity)
    {
        state.Map.ToChunkKey(entity.Get<Point>());
        ...
    }
}
```

**Comment by PodeCaradox** [comment]
The way i do is i have my systems with usefull iterations over Entitys with specific components, but inside i often need same functionality with one or two other entitys with a other component, like camera or my map for position calculation. So i use a static class which i can use everywhere and make them easy readable from outside: 
![grafik](https://user-images.githubusercontent.com/5760157/105612109-1b677f80-5dba-11eb-9d5f-13f31401f43f.png)

So Postransformer class is just a static class which i can use in every system, For example Movement class for my entitys or my InputSystem to calculate exact map coordinates out of the Screen Coordinates.

I really dont like the approach to have my methods in the Components itself :/
I also have only one World activ.

also this would no work:
private readonly Camera _camera;

My camera Component changes every update in position scale etc.
i cant pass a struct as a ref or can i?

**Comment by Doraku** [comment]
> The way i do is i have my systems with usefull iterations over Entitys with specific components, but inside i often need same functionality with one or two other entitys with a other component, like camera or my map for position calculation. So i use a static class which i can use everywhere and make them easy readable from outside:

Sure putting methods you reuse in multiple systems in a static class is definitely the way to go but if you only have one Map/Camera on a single entity (not even shared across multiple entities?), I am not sure it is worth it compared to just making it accessible as a static field/ instance passed in constructor/method, ect...

> I really dont like the approach to have my methods in the Components itself :/

That's why I also said extension methods :) But this is just personal style
```
// still neatly in a different class/file
public static class PointExtensions
{
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static Vector2 ToScreenPos(this Point position, Camera camera)
        {
            Vector2 worldPosition = Vector2.Transform(new Vector2(position.X, position.Y), Matrix.Invert(camera.Transform));
            return new Vector2((int)worldPosition.X, (int)worldPosition.Y);
        }
}

// simplified usage, camera can come from whatever solution you chose
position.ToScreenPos(camera);

```

> I also have only one World activ.

Then yeah you can disregard my warning about state in a static type if you only ever call your `Init` method once.

> also this would no work:
> private readonly Camera _camera;
 
> My camera Component changes every update in position scale etc.
> i cant pass a struct as a ref or can i?
> But thanks for you answer :)

It's just that from what you tell me  you could just have some king of
```
public static class Game
{
    public static Camera Camera;
    public static Map Map;
}

// the extension method above would just become
public static class PointExtensions
{
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static Vector2 ToScreenPos(this Point position)
        {
            Vector2 worldPosition = Vector2.Transform(new Vector2(position.X, position.Y), Matrix.Invert(Game.Camera.Transform));
            return new Vector2((int)worldPosition.X, (int)worldPosition.Y);
        }
}

```
and do the same without having to pay the price for an entity to access its components since you only have one of those and want to share them globally. Maybe you want to be 100% ECS and not rely to those kind of things but as Voltaire said the best is the enemy of the good, ECS is nothing but a tool and you need to chose the right tool for the right problem :)

Sorry if I am completely off course about your need as I don't have the big picture ^^"

**Comment by Exerionius** [comment]
@Doraku, I'm terribly sorry for interjecting into some other thread, but I don't want to spam new issues just for asking questions, and I couldn't find any forum with discussions.

Is there any way to shrink the World capacity back down? Let's say I created 150k entities in a world without capacity limitations, and then disposed all of them. It there any way to shrink the world's capacity back down and free up the unused memory?

**Comment by Doraku** [comment]
closing this, feel free to reopen if you want to discuss more :)
