### ISSUE TITLE
Empty Entity

### ISSUE THREAD

**Issue by onehundredfeet** [Doraku/DefaultEcs#108]
Maybe I can't find it, but it would be great to have an Entity.Empty static field to be able to initialize Entity records that haven't been created yet.

Great work btw.

**Comment by Doraku** [comment]
If you need to record the creation of a new entity, you need to use the [EntityCommandRecorder.CreateEntity](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/DefaultEcs-Command-EntityCommandRecorder-CreateEntity(DefaultEcs-World).md) method :)

**Comment by onehundredfeet** [comment]
What I mean, is I have stored an Entity in another structure. I want to initialize them rather than leave them uninitialized. 

like:

class Foo {
  Entity entity = Entity.Empty;
}

**Comment by Doraku** [comment]
Ah sorry I thought you were talking about EntityRecord. You can just use `default(Entity)` then, or even `new Entity()`, this will return an Entity which will always return false for its `IsAlive` property (and throw for any of its other methods/properties). I guess this would be equivalent to the Empty field you want.

**Comment by onehundredfeet** [comment]
Sure. Thanks. As it was a struct, it wasn't obvious if default(Entity) would do the trick or not.

Cheers.
