### ISSUE TITLE
how to use in unity 

### ISSUE THREAD

**Issue by 313364973** [Doraku/DefaultEcs#109]
i copy dll to unity plugins folder  ， error happend  System.Memory is the misssing with the current plattform

**Comment by 313364973** [comment]
I use nut for unity error happend Assembly references: 4.0.2.0 Found in project :4.0.3.0

**Comment by Doraku** [comment]
Hey, sadly unity does not handle nuget directly for now so I used [this (NuGetForUnity)](https://github.com/GlitchEnzo/NuGetForUnity) package to handle it. If you do it manually you would also need to add the dependencies of DefaultEcs (System.Buffers 4.5.1, System.Memory 4.5.4 and System.Runtime.CompilerServices.Unsafe 4.5.3).
An other weird problem of unity is that some dependencies of DefaultEcs are already present but with a different version and unity does not have BindingRedirect like we have in dotnet application, so the solution was to disable "Validate References" on the DefaultEcs.dll and System.Memory.dll in the unity editor
![image](https://user-images.githubusercontent.com/27510075/110096797-9ac77600-7d9e-11eb-9ba7-06cec075c560.png)
I think this option is not present in older version of unity though :/
Maybe if there is enough interest I will directly create a unity package to ease this setup :)

**Comment by 313364973** [comment]
thanks a lot very helpful。

**Comment by Doraku** [comment]
Np, I added a [faq](https://github.com/Doraku/DefaultEcs/blob/master/documentation/FAQ.md#how-to-use-defaultecs-in-unity) with those informations since I can imagine others encountering the same problem. Don't hesitate if you have an other problem, I have only tested basic usage of DefaultEcs in Unity on Windows and Android :)
