### ISSUE TITLE
AEntitySetSystem update sometimes is not consestent with it's component filters

### ISSUE THREAD

**Issue by nrader95** [Doraku/DefaultEcs#115]
As the title states, sometimes i get a really this weird behaviour where update might not be called on entity even though it should. Opposite case happens as well where i'm getting entities that do not have a components specified by filters.
The most frustrating thing is that this seems to be floating bug with everything working well 99% of the time.

And a bit of info:
DefaultECS version 0.16.0
I'm using your framework under Unity 2020.3.11f1, meaning it's run under some built-in version of the Mono.
Code is compiled into DLL against netstandart 2.0 and only then inserted into Unity.

**Comment by Doraku** [comment]
That's weird and worrisome, can you provide a little more info about your system/filter? Is it a simple filter (only With/Without), a reactive one (When...), some Either rules? does the problem occur in mono/multi thread? Is there a EntityCommandRecorder involved? Do you update your component value using `Entity.Get<T>` or do you use `Entity.Set<T>`? This should definitely not happen.

**Comment by nrader95** [comment]
No, all systems involved are single-threaded (construstor used is one without runner).
System execution order look like this pretty much:
System-1 sets component on the entity (component is struct, btw)
System-2 runs right after this, and the only filter it has is simple With filter (with typeof(MyComponent) inside)

And there is a system that later disposes some other entity which was stored inside one of components(HitComponent) on entity with MyComponent ( this cleanup system is single-threaded as well).
And what i'm getting is that system-2 sometimes getting already dead entities inside HitComponents, meaning it's update seems to be not executed on the frame before that, apparently.

**Comment by nrader95** [comment]
EntityCommandRecorder is not involved, in fact we are not using it at all.
We are not updating component, in fact it's empty strust whose sole purpose as helping with filtering entities.
But in System-1 it's setted this way:
entity.Set(new MyComponent());

**Comment by Doraku** [comment]
So System-1 set `MyComponent` on some entities and you get entities without this component in System-2 despite the `With(typeof(MyComponent))` rule? Do System-1 also have rule `Without(typeof(MyComponent))`?
Does the cleanup system only dispose entities which are not directly inside its inner set? (indirectly inside the HitComponent?) or can they also be directly inside the system?

**Comment by nrader95** [comment]
System-1 doesnt have `Without(typeof(MyComponent))`
The problem is that System-2 does not call update on the entity on which component was set, not on the same frame at least.

**Comment by Doraku** [comment]
Yeah from what you say this definitely should not happen. Can you provide the full systems code? I guess you did not do some subscribe on entity component event too? (`World.SubscribeComponentAdded/Changed`)

**Comment by nrader95** [comment]
No, i did not subscribe to anything.
As for code, the systems are quite large and have many other dependecies so that's problematic.
But i guess i can cut the most relevant parts.
That how system-1 sets components in question:
```
                entity.Set(
                    new HitComponent(
                        hitPoint,
                        HitType.UnitHit,
                        parent,
                        hitEntity
                    )
                );
                entity.Set(new ExplosionEventComponent());
```
Now this is the head of system-2:
```
    [With(typeof(ExplosionEventComponent))]
    public class ExplosionEventSystem : AEntitySetSystem<float>
```
And this is a part of this systems update:
```
        protected override void Update(float state, in Entity shellEntity) {
            ref var hitComponent = ref shellEntity.Get<HitComponent>();
            if (hitComponent.WeaponEntity.IsAlive) {
```

So by the time update is finally called weapon entity which was alive at the time of setting is already dead, and that's how i assumed updated was not called at least once.

**Comment by Doraku** [comment]
hum is it possible that multiple `HitComponent` reference the same entity in `WeaponEntity`? does the entity dispose only occur  in the later system or can it also happen in System-2?

**Comment by nrader95** [comment]
It's indeed possible to have several hits originated from one weapon, but HitComponent only stores data inside.
As for Dispose, it happens later

**Comment by Doraku** [comment]
It's hard to pin point what is going on without the full picture, I have similar code in my project and this never occurred to me. Only cases when the enumerated entities of an entity set could be wrong would be if you are changing components that would make an entity be removed or added on your current set (even worse if doing so in multi threading). Normally to counter this you would have to set the `useBuffer` parameter of the system constructor to `true` so that the set entities are copied, that way even if the set change as you are processing its entities from the buffer you would not end up with something invalid. But here it is a referenced entity from your `HitComponent` that seems wrong. I guess this is not a public project :/

**Comment by nrader95** [comment]
Well, ExplosionEventSystem actually does have Remove<ExplosionEventComponent>()  inside update method. So, i tried to use constructor with `useBuffer` parameter if that's the culprit.
No luck.

**Comment by nrader95** [comment]
Hmm, although disposes happen at the end, we use Remove<ExplosionEventComponent>() inside `ExplosionEventSystem`. So i tried to test it by using constructor with `useBuffer` parameter(in fact i tried to add it to anithing related to HitComponent or disposing). But no luck.

**Comment by Doraku** [comment]
There is probably somewhere a dispose on the wrong entity (the weapon entity), I don't really see any other way since you are single threaded. An alive Entity can only return false for `IsAlive` if it was disposed.

**Comment by nrader95** [comment]
Yeah, but none of the two systems have any entity dispose lines so the only way for dispose to happen is to skip update cycle.

**Comment by Doraku** [comment]
Couldn't one entity with a `HitComponent` remains from a previous frame for some reason? How are those cleaned up?

**Comment by nrader95** [comment]
There is a dedicated system at the end of execution cycle that calls dispose on entities that are to be deleted.
```
    [With(typeof(DestroyComponent))]
    public class DestroySystem : AEntitySetSystem<float> {
        public DestroySystem(World gameContext) : base(gameContext, true) { }

        protected override void Update(float state, in Entity entity) {
            if (!entity.Has<DestroyComponent>()) {
                LogError("Entity is part of EntitySet, but it does not fit the AEntitySetSystem component filter!");
            } else {
                ref var destroyComp = ref entity.Get<DestroyComponent>();
                if (destroyComp.DestroyGameObject) {
                    if (entity.Has<ViewComponent>()) {
                        ref var gameObject = ref entity.Get<ViewComponent>().gameObject;
                        Assets.Destroy(gameObject);
                    }
                }
            }
            entity.Dispose();
        }
    }
```
Speaking of this system, we also got entities that didn't match the filter here a few times (hence this weird Has<DestroyComponent> inside if statement).

**Comment by Doraku** [comment]
ehhhh that really shouldn't be possible. You said this is running on Unity mono backend? WindowsStandAlone target? Can you try switching to non reflection entity set declaration just in case? `gameContext.GetEntities().With<DestroyComponent>().AsSet()` to pass to the base constructor. I will try to see if I can reproduce this issue.

**Comment by nrader95** [comment]
Tried to change world parameter constructor to EntitySet one, but no positive changes here.

**Comment by nrader95** [comment]
Well it seems like the problem at the top of topic was indeed in the fact entity was deleted (in a non-so-obvious way).
As for problem with destroy system, it didn't occured after this, so i guess this issue can be closed.

**Comment by Doraku** [comment]
Glad that you found the culprit code. Do you think something could be done at the framework level to make it more obvious when a dispose occurs or was it really something specific to your systems setup?

**Comment by nrader95** [comment]
No, it was specific to my code.
