### ISSUE TITLE
World.Has<T> returns wrong value

### ISSUE THREAD

**Issue by nrader95** [Doraku/DefaultEcs#117]
As the title stattes, i get wrong value when world actually has component in questions.
And i think i know what causes it as well:
world code:
```
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public bool Has<T>() => ComponentManager<T>.Get(WorldId)?.Has(0) ?? false;
```
ComponentPool code:
```
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public bool Has(int entityId) => entityId < _mapping.Length && _mapping[entityId] != -1;
```

So my world Id was 2, and in debugger i saw 0 for index 2 of _mapping, too. All good, except ComponentPool checks index zero, and so i get false instead of true as result.

**Comment by Doraku** [comment]
The entityId 0 is basically reserved for the world components (allow components of the world to be stored the same way as entity components and share them). The ComponentPool is an instance, the mapping is for entity ids, the world id is used to get the correct instance through ComponentManager. Everything looks as expected?
I am really starting to wonder if there's not something that goes horribly wrong in unity mono. Sorry I still haven't had the time to check it, pretty busy currently :/ but I haven't forgotten your other issues!

**Comment by nrader95** [comment]
So does that mean World.Has<T> would not check entities of that world and only components set directly? If so, it should probably stated more directly in doc of method, because now it says it returns whether world has component or not, but it's not obvious that entities are NOT included in the check.

**Comment by Doraku** [comment]
ahhh I get the confusion now! yeah indeed this does not return whether there is some entities with the given component type but if the world itself has a component of this type (new concept). I will add more information in the comment to reflect that
