### ISSUE TITLE
How to properly handle collisions

### ISSUE THREAD

**Issue by lamossus** [Doraku/DefaultEcs#122]
This is not strictly defaultEcs question, so I hope it's allowed to post it here.

I have a collision system that checks whether objects collide with each other and returns some collision info (like penetration depth and collision normal). I need to apply some changes to entities based on that info in other systems (movement system, damage system, etc.), so I can't just flag the entity with "Collided" component/bool, I actually need to store that info. Now, the problem that I ran into is that, since entities can collide with many other entities, not just one, I need to store all collision info in some collection. But all collections in C# are passed by reference, as far as I'm aware, while all of my components are structs that are passed by value. So if I store collisions inside the Collider component it will have one reference type while all other components and all of their fields will only ever have value types. I don't really like having that inconsistency in components, it already caused some problems while trying to find a bug in my movement system, so ideally I would like to somehow fix it. But I'm not really sure how, where else would collision info be stored if not in a component?

**Comment by Doraku** [comment]
hum someone started a discussion on this subject [here](https://github.com/Doraku/DefaultEcs/discussions/121) maybe you will find some insight in our exchange?

On the struct/class thing, I am only speaking for DefaultEcs but I made it specifically so it can handle both struct components and class components. While struct components are preferable for cache locality when processing entities some problems are easier the OoP way so I have no problem mixing the two philosophies (but as you said you need to be careful between, struct, ref and everything ^^").
