### ISSUE TITLE
Crash when disposing entities

### ISSUE THREAD

**Issue by AridTag** [Doraku/DefaultEcs#123]
Hi I'm trying to use DefaultEcs for an MMO emulation project. When the users client is closed a couple of network connections are disconnected. There is an entity for each of the network connections the client makes.

I've been experiencing a crash when trying to Dispose of those entities. 

```csharp
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DefaultEcs.EntityMap`1.DefaultEcs.Technical.IEntityContainer.Remove(Int32 entityId) in Z:\GitWorkspace\*******\src\DefaultEcs\EntityMap.cs:line 242
   at DefaultEcs.Technical.EntityContainerWatcher.Remove(EntityDisposedMessage& message) in Z:\GitWorkspace\*******\src\DefaultEcs\Technical\EntityContainerWatcher.cs:line 104
   at DefaultEcs.Technical.Command.Executer.Execute(Byte[] memory, Int32 commandLength, List`1 objects) in Z:\GitWorkspace\*******\src\DefaultEcs\Technical\Command\Executer.cs:line 89
   at DefaultEcs.Command.EntityCommandRecorder.Execute() in Z:\GitWorkspace\*******\src\DefaultEcs\Command\EntityCommandRecorder.cs:line 214
   at *******.Server.UpdateLoop(Object obj) in Z:\GitWorkspace\*******\src\*******\Server.cs:line 167
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

When a network connection is closed and it's not a connection associated with a player in the world a NetworkClientDisconnected component is added to the entity and you can see in the following log that it gets picked up by the NetworkClientDisconnectedCleanupSystem, if it's associated with a player in the world it will get a PlayerDisconnectedComponent and get picked up by the PlayerDisconnectedCleanupSystem.

Both of these systems use an EntityCommandRecorder to do the disposing and then in PostUpdate if any commands were recorded it publishes a message to have the server add the recorder to a queue to be processed when all systems have completed the current Update.

```
dbug: ******.Ecs.Systems.NetworkClientDisconnectedCleanupSystem[0]
      Disposing entity Entity 1:2.0
dbug: ******.Server[0]
      Queuing entity commands
dbug: ******.Ecs.Systems.NetworkClientDisconnectedCleanupSystem[0]
      Disposing entity Entity 1:3.0
dbug: ******.Server[0]
      Queuing entity commands
------------------------------------
-- Client closed here --------------
------------------------------------      
dbug: ******.Ecs.Systems.NetworkClientDisconnectedCleanupSystem[0]
      Disposing entity Entity 1:3.1
dbug: ******.Server[0]
      Queuing entity commands
dbug: ******.Ecs.Systems.World.PlayerDisconnectedCleanupSystem[0]
      Disposing entity: Entity 1:2.1
dbug: ******.Server[0]
      Queuing entity commands
```

My original thinking was that I must be accidentally disposing the same entity twice _somehow_ but I could not figure out where I was doing it if I was. So I ended up cloning the DefaultEcs repo and adding it as a project to my solution so that I could modify Entity.cs and have it do a Debug.WriteLine in its Dispose method to see exactly what entities are being disposed leading up to the crash and hopefully prove it wasn't my fault.

These are the Debug.WriteLines from Entity.Dispose()
```
Entity.cs - Disposing Entity 1:2.0
Entity.cs - Disposing Entity 1:3.0
Entity.cs - Disposing Entity 1:3.1
Entity.cs - Disposing Entity 1:2.1
```

This is a screenshot of the _mapping array in ComponentPool.cs at the point of the exception
![image](https://user-images.githubusercontent.com/1786930/127084028-82c26fe4-99f2-4ce7-89d3-7ebd62b51406.png)

It looks like this is getting corrupted somehow? I'm not really sure. Any help is greatly appreciated

**Comment by Doraku** [comment]
From the look of it, the error occurs when accessing the previous component pool. Since you already have the source to debug, could you try a small change?
https://github.com/Doraku/DefaultEcs/blob/ce21ac209010f968e5165adb83b4b7d2f8d09b3f/source/DefaultEcs/Technical/EntityContainerWatcher.cs#L104
https://github.com/Doraku/DefaultEcs/blob/ce21ac209010f968e5165adb83b4b7d2f8d09b3f/source/DefaultEcs/EntityQueryBuilder.cs#L358
Change the message type from `EntityDisposedMessage` to `EntityDisposingMessage`, I tried to replicate what I though was occuring but couldn't make it fails :/, still this change is worth a shot (basically the subscription order is not guaranteed and maybe the component is removed from the pool before the callback to remove the entity from the EntityMap is called, I made the Disposing/Disposed message specifically for this but this subscription slipped pass me). I will keep looking into it.

**Comment by AridTag** [comment]
I do indeed have multiple Maps with the same key. This change does appear to have fixed it!

**Comment by Doraku** [comment]
Thank you for giving all those infos, made finding the problem much easier :)
