### ISSUE TITLE
Plans for the future ? 

### ISSUE THREAD

**Issue by genaray** [Doraku/DefaultEcs#135]
Thanks again for this wonderfull ECS !!

Just out of curiosity, do you have any plans for the future ? ^^ 
Like further Performance upgrades or other nice features ?

**Comment by Doraku** [comment]
hey, I can't say I have some big plan but at least here are my short/mid term objectives:
- allow the creation of custom entity container with the existing EntityQueryBuilder fluent syntax, not something I had in mind at first but the code recently evolved in such a way that it would be interesting to allow people to design entity container with the memory representation that they need. This does not mean that there won't be more new containers provided in the framework (like SortedSet) but it would be interesting to allow people to experiment and see what would be good to add directly in the framework
- allow storing multiple components of the same type on the same entity #118. It would be great to have and this is what I was working on before switching on the previous point haha. I like to work by iterating with only a rough idea of where I want to go, some features just reveal themselves :D (big contrast with my work where I restrict myself a little!)
- add the ability to create entity template #114

Some others things I would like to do and would probably jump on if I get a good idea to do it:
- add a special component type to reference an other entity component (like the parent position). This would give a built in way to create hierarchy between entities and design stuff
- precache the components id of entities when you need multiple component types to speed up system processing, I am still looking for a cleaver trick to reduce cache misses

I can't really give any timeframe as I am doing this in my spare time which is already sparse sometimes. I may be working on one of my other projects (like right now for example ^^") but I always try to answer every question and if an issue pick my interest I may jump ship :p
