### ISSUE TITLE
ManagedResource setting is slow

### ISSUE THREAD

**Issue by nrader95** [Doraku/DefaultEcs#136]
As the title states, ManagedResource can be problematic due to its performance.
In my case, we used it to load 3D models (and some other stuff  inside Unity3D, but mostly them), making an instance of it while also setting corresponding components on entity to work with it. 
Turns out it was bad idea - ManagedResources have quite noticeable overhead when when you try set them often, and we did (we spawned shooting effects and shells models and that's something that usually happen in big number is a short amount of time...), which resulted in freezes.

Anyway, while i'm already done with the freezes in my project by not using ManagedResource anymore, i think you should look at their performance.

**Comment by Doraku** [comment]
The ManagedResource handling was made to circumvent the problem of component data that could not be serialized and automate their loading. I made it with the idea that it would only be used during initialization of your world to preload all the resources (texture, sound, ...) you would need and not during the hot path. The overhead you are experiencing should probably be mostly the actual resource loading :/

One way you could try to mitigate this is by having simple entities only with a ManagedResource component one for each resource you will need during your scene to trigger the loading during the initialisation. Then later on when you create your entities for effects, the resources will already be loaded and the resource manager will simply return the existing instance.

An other overhead you are experiencing could be from creating entities and setting components for each new effect. While this certainly not slow, if you need to create a lot of entities in a single frame it could become noticeable. A strategy I am using in my game for particles is that I create a pool of entities with all the needed base components to display an effect and disable them. Then when I need to create entities for my explosion effects I just take an entity from the pool, set the components as needed and reenable it. Once the effect dies the entity is disabled, stripped of the excess components I may have set on it and put back in the pool.

Maybe I could create an AsyncResourceManager so the resource are loaded asynchronously, I will see what can be done.

**Comment by nrader95** [comment]
> The overhead you are experiencing should probably be mostly the actual resource loading :/
It's definitely not. I rewrited my code to load my resources without ManagedResources and their managers(basically all my old code minus ecs part), and freezes disappeared. So it's not loading process, i'm sure of it.

**Comment by Doraku** [comment]
hum, what was the type you were using as TInfo in your ManagedResource? a string or something custom? The code of AResourceManager is quite simple and goes something like this:
- callback on ManagedResource component added (small overhead of an event, entity initialisation and component value retrieved, this probably can be ignored)
- internal lock in AResourceManager (since you are setting your component in single thread the impact should also be low)
- dictionary try get using the TInfo (if the GetHashCode/Equals of the type is badly defined, maybe this is where the problem occurs?)
- actual load of the resource if needed (should be what takes the most time)
- call the OnResourceLoaded override of the AResourceManager

**Comment by nrader95** [comment]
>hum, what was the type you were using as TInfo in your ManagedResource? a string or something custom?

I used string as TInfo. (it was data path to my asset)

**Comment by Doraku** [comment]
Just tried setting ManagedResource in a single frame (my TInfo is also a string), I didn't notice any slow down up to 5k, after that I think some slowdown can expected without using some other tricks like a pool :/ how many objet were you spawning in a single frame? if its much less something else is going on.

**Comment by nrader95** [comment]
It was less, but it keep in mind i'm using your framework under Unity3D, and that means old Mono & netstandart2.0.
