### ISSUE TITLE
AEntitySetSystem<T> invokes runner in single-threaded mode

### ISSUE THREAD

**Issue by nrader95** [Doraku/DefaultEcs#140]
So we encounteres synchronization lags in our single-threaded (!) systems.
After i bit of reading through the source code of AEntitySetSystem<T>, culprit seem to be this:
```
                    _runnable.CurrentState = state;
                    _runnable.EntitiesPerIndex = Set.Count / _runner.DegreeOfParallelism;

                    if (_runnable.EntitiesPerIndex < _minEntityCountByRunnerIndex)
                    {
                        Update(state, Set.GetEntities());
                    }
                    else
                    {
                        _runner.Run(_runnable);
                    }
```
This triggers the use of runner when we don't need it.

Other systems that support runners seems to have this bug as well.

**Comment by Doraku** [comment]
Sorry for the late reply, didn't get much free time the last weeks sadly. Did you mesure the actual impact? This just add two virtual calls (`IParallelRunner.Run` and `IPArallelRunnable.Run`) which should be pretty negligible next to the actual processing of all the entities.

**Comment by nrader95** [comment]
I dont know about pure .NET enviroment, but in Unity the performance impact was noticeable (we deep profiled our code base and that's how we found this).

**Comment by nrader95** [comment]
In fact, anything that uses default System.Task<T> seems to perform poorly under Unity in my experience.
