### ISSUE TITLE
No longer able to remove an added component from ComponentAdded or ComponentChanged subscriber

### ISSUE THREAD

**Issue by dkominek** [Doraku/DefaultEcs#146]
Hey, I've been using DefaultEcs for a while now and updated from 0.15.2 to 0.17.0 recently. 

It looks like it is no longer possible to remove an added component in a ComponentAdded or ComponentChanged subscriber. I did some digging into the changes made between those versions, and it looks like the issue is caused by a change made in version 0.16.0 to the Entity.Set method. 

The Entity.Set function was changed from using the component argument on [line 184 in 0.15.2](https://github.com/Doraku/DefaultEcs/blob/d3e988e929fb5682c721bfabf7fc826e083f2e6f/source/DefaultEcs/Entity.cs#L184) to using a call to Entity.Get instead on 
[line 89 in 0.16.0](https://github.com/Doraku/DefaultEcs/blob/ab85d19031c0c8b2f0c11a9ff19431d94579520a/source/DefaultEcs/Entity.cs#L89).

Is there any way you could include a Entity.Has check before using Entity.Get here? This issue will block my upgrade path of this great library.

You can reproduce this by creating a subscriber on ComponentAdded, and removing the component being added from in that subscriber.

```csharp
public class ComponentRemover {
    public ComponentRemover(World world)
    {
        world.SubscribeComponentAdded(ValidateComponent);
    }

    private void ValidateComponent(in Entity entity, in MyComponent component)
    {
        // maybe some validation happens here and we need to remove the component...
        entity.Remove<MyComponent>(); // ERROR: this line will produce a IndexOutOfRangeException
    }
}
```

Something like below or if you have a better method:
```csharp
if (Has<T>()) 
{
    ComponentManager<T>.GetPrevious(WorldId)?.Set(EntityId, ? Get<T>() : null);
}
```

**Comment by Doraku** [comment]
Thanks for reporting you are totally right I will add some tests so this regression no longer occurs in the futur.

**Comment by dkominek** [comment]
Any rough estimate of when a fix will be released? I will stay on 0.15.2 until then :)

**Comment by Doraku** [comment]
Really sorry I took this long to fix this, start of the year has been as crazy as the end of the previous one ^^" I hope I'll get some free time more frequently!

**Comment by dkominek** [comment]
All good! I'm just happy you find any time to work on this library 🤗
