### ISSUE TITLE
Entity Dispose Within a System

### ISSUE THREAD

**Issue by LRFalk01** [Doraku/DefaultEcs#150]
I'm having an issue understanding when I am allowed to dispose of an entity. It appears as if even if being disposed without multithreading, a disposed entity breaks the world. I have an example project that demos this.

https://github.com/LRFalk01/testing_ecs/blob/main/PingSystem.cs#L34

With this dispose within the system, the world appears to remove the wrong entity from it's internal array, however the set for the system holds the correct reference and tries to run for entity2 which the world is no longer aware of. Kind of hard to explain.

Console Output:
```
Entity 1:1.0: ping 1
Entity 1:2.0: is not alive
Entity 1:2.0: is not alive
```

The ping system disposes entity 1, then goes to run again for entity 2, but the world thinks that entity is removed. If I go to run the system again, it's somehow aware of entity 2's existence but the world is not.

**Comment by Doraku** [comment]
Hello sorry for the late reply (holidays and happy new year!). When you want to dispose (or do any operations that would make your entity set change, like removing a component when the set is expecting it), you need to use a buffer to copy the entities before processing them. The `AEntitySetSystem` actually have a constructor override just for that which takes a `bool useBuffer` parameter. I have cleaned up a little the constructors to make this behavior a little more visible for the next version coming but I also need to document it a little better.
