### ISSUE TITLE
AEntityMapSystem missing

### ISSUE THREAD

**Issue by monodop** [Doraku/DefaultEcs#155]
We have the following query types:
```cs
.AsSet()
.AsMap()
.AsMultiMap()
```

but we only have the following helper system base classes:
```cs
AEntitySetSystem<TState> // Corresponds to .AsSet()
AEntityMultiMapSystem<TState, TKey> // Corresponds to .AsMultiMap()
```

Is there a reason that we're missing `AEntityMapSystem<TState, TKey>`  to correspond to `AsMap()`?

**Comment by Doraku** [comment]
Systems are used to process multiple entities. The goal of a map is to give quick access in o(1) to a specific entity. Processing all the entities of a map doesn't really make much sens as you would need to get all the existing keys to retrieve all the entities, it would be much faster to just use a normal set instead (the only difference between the two would be unicity on the `TKey` component of the map).

**Comment by monodop** [comment]
Alright, so if I wanted to have fast iteration and fast lookup, I would need both a set and a map?

**Comment by Doraku** [comment]
Yes as they serve different purposes and are not cached the same way in memory.
