### ISSUE TITLE
Second rules query returns same entities as previous query

### ISSUE THREAD

**Issue by acampbellb** [Doraku/DefaultEcs#164]
This maybe an API usage issue, so perhaps what I am expecting is not correct. I have 2 consecutive (different) rules queries which I materialize with AsEnumerable (same result using AsSet as well), and the second query always returns the same set as the first one. In the following example the first query returns entities 3 and 4 both of which have a string and float component. In the second query it should enumerate only entity 2, but it returns 3 and 4 again.

(Note: the editor removes the generic types, so I've put them in the comments)

`var entity1 = _world.CreateEntity();
entity1.Set<int>(1);  // int
entity1.Set<float>(1.1f);  // float

var entity2 = _world.CreateEntity();
entity2.Set<int>(2); // int

var entity3 = _world.CreateEntity();
entity3.Set<string>("test3");  // string
entity3.Set<float>(3.1f);  // float

var entity4 = _world.CreateEntity();
entity4.Set<string>("test4");  // string
entity4.Set<float>(4.1f);  // float

var entities1 = _world.GetEntities()
    .With<string>().With<float>()  // with string & float
    .AsEnumerable();

foreach (var entity in entities1)
{
    Console.WriteLine($"query result entity: {entity}");
}

var entities2 = _world.GetEntities()
    .With<int>()    // with int
    .AsEnumerable();

foreach (var entity in entities2)
{
    Console.WriteLine($"query result entity: {entity}");
}`

Output:

query 1 result entity: Entity 1:3.0
query 1 result entity: Entity 1:4.0
query 2 result entity: Entity 1:3.0
query 2 result entity: Entity 1:4.0

**Comment by acampbellb** [comment]
Nevermind. I had compiled your library as a .NET Core 6 project, using the .NET standard library things worked as expected.

**Comment by Doraku** [comment]
sorry for the laaaaaate reply, as it seemed you had resolved the issue on your end I completely forgot about it >_< anyway tried quickly your code in the unit tests and everything was working as intended :)
