### ISSUE TITLE
ComponentAddedHandler or ComponentChangedHandler are not called for Components of the world

### ISSUE THREAD

**Issue by danielscherzer** [Doraku/DefaultEcs#165]
Thanks for your amazing library.

I want to monitor addition of a `bool` component to the world:

``` C#
using World world = new();
bool called = false;
world.SubscribeComponentAdded((in Entity _, in bool b) => called = b);
world.Set(true);
```
When I execute the code `called` should be `true`, but it is `false`.

If I do the same for an entity
``` C#
using World world = new();
bool called = false;
world.SubscribeComponentAdded((in Entity _, in bool b) => called = b);
var e = world.CreateEntity();
e.Set(true);
```
`called` is set to `true`, as expected. Is this the intended behaviour or is this a bug?

Thanks for your time,
Daniel

**Comment by Doraku** [comment]
hum I didn't add subscriptions for world components but it wouldn't be too hard to do (as the current subscription is only for entity components) so for now it is intended ^^". Thanks for the feed back :)
