### ISSUE TITLE
WhenAdded / WhenChanged not updating for World component

### ISSUE THREAD

**Issue by slimshader** [Doraku/DefaultEcs#177]
Hi,

I have a system with
```
.WhenChanged<Board>().WhenAdded<Board>()
```
 EntitySet, it runs Update when entity is created likes so:
```
_world.CreatEntity().Set(new Board());
```
but stops being called when I change the line to:
```
_world.Set(new Board());
```

**Comment by Doraku** [comment]
Just answering it there too but world component (the 3rd line) is not the same as an entity component so it's normal that it's not picked up by the entity set. I do have plan to add a world variant of calls like [World.SubscribeComponentAdded](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/World.SubscribeComponentAdded_T_(ComponentAddedHandler_T_).md) so you can subscribe on world component change too in the futur.
