### ISSUE TITLE
Make World Id Public

### ISSUE THREAD

**Issue by AustinSmith13** [Doraku/DefaultEcs#191]
Hello, we are using DefaultECS in our project and we need to access the id of a world.

The reason why we need access to this is because we are writing an Extension, however there is not reliable way to discern a world from another. This means our entity extension methods are not specific to any world.

The fix to this problem is to create a getter to _worldId.

**Comment by DagobertDev** [comment]
Another possible solution for your problem could be a world level component that contains an id.

**Comment by AustinSmith13** [comment]
Oh that's a good idea, I left a pull request incase anyone is interested. I'll try adding a world component, it will probably solve my issue.
