### ISSUE TITLE
add WithAny filter for EntitySet

### ISSUE THREAD

**Issue by Doraku** [Doraku/DefaultEcs#24]
Adding two filter ComponentEnum in EntitySet to handle one case of those rules would be easy but it would double the checks needed on component change.
It would also be possible to add one filter for each of those rules so that you could define multiple family (`WithOneOf<A, B>().WithOneOf<C, D>()` should this be handled as `WithOneOf<A, B, C, D>()` or two separate rules?) then each familly would add one check, kinda snowballing...

There may be a way to simplify the rules application so we don't add needless check when a group is not defined. To look into.

bad method names pending

edit: doing it

- [x] EntitySetBuilder.WithAny(type[])
- [x] WithAnyAttribute
- [x] EntitySetBuilder.WithAny<>() helper methods
- [x] code documentation

**Comment by archnem** [comment]
Thanks so much.  I had two different systems to draw sprites vs. animated sprites, now I can consolidate into one.

**Comment by Doraku** [comment]
Thank you for asking for it, made me refactor the rule creation in a much more powerful way ^^
