### ISSUE TITLE
Create communication channel

### ISSUE THREAD

**Issue by Morasiu** [Doraku/DefaultEcs#28]
First of all. Great project. I really appreciate it and I'm gonna use it in my own project.

My proposition is, could you create Discord server or something like Discrord, where all users (and you) could cooperate?

**Comment by Doraku** [comment]
Thank you for the kind words!
Do you think github issues do not serve this purpose well enough? If you want to propose features or need some help (I know the documentation is lacking in some area...) I will be happy to oblige.
If my framework become the next big thing (haha) maybe some other means of communication would be needed but for now, I only know of 3 users so a Discord might be overkill ^^".

**Comment by Morasiu** [comment]
Github Issues are more like forum. Maybe somebody will want to show off their new creation and just ask simple question. But you are probably right. It could be overkill for just 3 people. Anyway keep that idea in mind :)

**Comment by Doraku** [comment]
If this get too impractical or there is more demand for it I'll set up something. I am not crawling under questions currently :)

**Comment by Doraku** [comment]
so I went ahead and created a [gitter](https://gitter.im/Doraku/DefaultEcs#) page, seemed like less hassle than a discord channel and you can use your existing github account, let's see how it goes!
