### ISSUE TITLE
Add screenshots to Sample section in README.md

### ISSUE THREAD

**Issue by Morasiu** [Doraku/DefaultEcs#29]
It would be nice to see what you can create with your framework. Also think about adding compiled and zipped games in Relase section on GitHub for quick download 👍

**Comment by Doraku** [comment]
Obviously current samples are quite lacking. I meant to create a readme page for them with more details and screenshot/gif but they are so underwhelming I didn't bothered. 
My pet game project may be a little more impressive but I have probably spent much more time on making this framework than making it x) and it's not really in a demo state (hope to get there this year).
A more simple and time efficient thing I could do would be to get some samples of other frameworks and translate them with DefaultEcs but I don't know how ethical that is.

**Comment by Morasiu** [comment]
Trust me. They are fine :)

**Comment by Doraku** [comment]
quick and dirty done ^^"
