### ISSUE TITLE
Allow use of Non-generic types for EntitySetBuilder

### ISSUE THREAD

**Issue by captkirk88** [Doraku/DefaultEcs#31]
Currently the EntitySetBuilder uses generics on all but WithAny.  Generics limits the ability to create entitysets from unknown types at runtime.  For example, referring to #20 , the use of generics makes that issue impossible to resolve because type names read from a file cannot be parsed into generic arguments (as of C# 7.2).

**Comment by Doraku** [comment]
I choosed the generic way because I found it less verbose and it removes the need to use reflection internally to create the actual filter. I didn't want to limit the number of types in the WithAny rule which is why it has the type[] variant relied on by the generic extension methods.
I could easily add such a method for With and Without if needed (your target is EntitySetBuilder.With(params Type[]) and EntitySetBuilder.Without(params Type[]) right? Actually it's much better to add them now with the changes done to the builder to handle WithAny!) but I'am just trying to understand the use-case.
What are you trying to do that you do not have access to your component types at compile time?

**Comment by captkirk88** [comment]
My use-case is a template system where I can load and create entities from a file instead of hardcoding their components into a factory class/method.

**Comment by Doraku** [comment]
So what you really need is #20?
By the way there is almost all the code needed to implement this issue (but it's internal), I just haven't decided yet on the final api :/.

Where does EntitySetBuilder fit in this though?

**Comment by captkirk88** [comment]
Those are exactly what I need.  Thanks!

**Comment by captkirk88** [comment]
Yes I thought about submitting a pull request for it but I didn't know what you had done already on #20 and it is a small change.

**Comment by Doraku** [comment]
It's not a huge change but I won't be able to do it before tomorow (sorry it's pub night ^^).
If you are curious it's just moving some code from AEntitySet.GetEntitySetFactory, nothing more.

Eh a small change? How do you handle it, just a wrapper above ISerialize.Deserialize?

**Comment by captkirk88** [comment]
I meant this issue being a small change.  For something like Artemis that doesn't have built in serialization I used Newtonsoft Json to serialize the components since the ID had to be created by Artemis due to the entity recycling.

**Comment by Doraku** [comment]
33306109f7974289be30b4322241799d4b6441f7 done
I probably won't create a new release until this week end.

**Comment by captkirk88** [comment]
Thanks.  If I were you, I would integrate continuous integration services like appveyor.  They are free for open source projects.  It is useful for creating release builds or publishing to nuget after committing to the repo without having to do it manually all the time.  Granted, the advised route (don't make the mistake I did) is to have a beta branch and merge it into the master when you want a good build to be pushed to nuget or users.

**Comment by Doraku** [comment]
I'll probably look into it if too many people start contributing. For now I have a small .bat to play my tests and package the nuget on success. Then after some time with this "pre-release" on my game project to be confident that everything works as expected, I push it to nuget.
I already have to deal with CI configuration and branch hell at work, I prefer to keep it simple at home ;)

**Comment by captkirk88** [comment]
No argument there.  I really like the performance of your ECS compared to Artemis.  Granted, yours has less features and is a little harder to work with in certain situations (like the one I encountered in this issue) but performance is what matters at the end of the day.

**Comment by Doraku** [comment]
Don't hesitate to shoot me an issue. I try to keep a streamlined api as simple and clean as possible but it's derived from my use-cases encountered as I build my game so there's probably lot of features I haven't thought of.
Glad the performance suits you! It was a strong point when I started building this ^^
