### ISSUE TITLE
add component types filter on ISerializer

### ISSUE THREAD

**Issue by Doraku** [Doraku/DefaultEcs#32]
There is probably some component type which you do not want serialization (texture, ...), their should be a way to ignore them.

**Comment by prime31** [comment]
I’m in the process of building a serializer now. This is just my opinion, but I don’t think DefaultECS needs a serializer in the library. Serialization is so game specific that it would be nearly impossible to make one that would be useful.

**Comment by Doraku** [comment]
I've been wondering for a while to leave both my serializers in or move them to their own package, only leaving IComponentReader and IComponentTypeReader in the framework to at least keep an open door for people wanting to make their own serializer... Since they doesn't bring extra dependencies there is no harm for now, maybe one day I won't be too lazy to actually do it.

**Comment by prime31** [comment]
Haha. I know the feeling about being lazy ;)
