### ISSUE TITLE
Entity.Has returns true incorrectly....or Entity.Remove doesn't remove

### ISSUE THREAD

**Issue by prime31** [Doraku/DefaultEcs#39]
I'm running into this issue regularly and it's pretty easy to reproduce. Basically, the following code ends up falling through to the `log` call. Now the odd bit is that it isn't 100% of the time. If I create 50 Entities about 25 of them will exhibit the bug.

```csharp
entities[i].Remove<BoxCollider>();

var hasBoxCollider = entities[i].Has<BoxCollider>();
if (hasBoxCollider)
     Debug.Logger.log("why do we still have a BoxCollider???");
```

To reproduce
- add a bunch of Entities with some Components
- in a System some time later, call `Remove` then check for the Component with `Has`

<img width="692" alt="Screen Shot 2019-04-10 at 10 38 04 PM" src="https://user-images.githubusercontent.com/60377/55933474-403d3380-5be2-11e9-8a36-b83cd2f674e8.png">

I am not sure if this is related or not, but the System is also getting duplicate Entities in the EntitySet:

![bug_2](https://user-images.githubusercontent.com/60377/55933917-c60dae80-5be3-11e9-9d91-f18ce94bd360.png)

Any ideas what is going on with this one? I don't see any obvious issues in the `Remove` or `Has` code paths...

**Comment by Doraku** [comment]
That seems quite odd. What is your filter on the EntitySet? If the component you are removing is part of the filter that could explain what you end up with.
Also are you performing the remove in a single or multiple threads?

**Comment by prime31** [comment]
This system is all single threaded. The filter is WithAny<BoxCollider, CircleCollider>().Without<PhysicsCollider>() so I am mutating the EntitySet like a fool while iterating it. The System is basically there to take any *Collider struct and convert it to unmanaged memory in a PhysicsCollider, which wraps all Collider types. Lemme try switching to EntityRecorder and see if that does the trick. It was late at night and I wasn’t thinking straight trying to mutate the Span like that! Thanks for pointing out my ignorance ;)

**Comment by Doraku** [comment]
Yeah the last entity of the set is moved to your current index when the component is removed, which is why it logs that the component is still here (if you check the debug info of the entity it has probably changed) and since the span length does not change, you see a duplicate at the end.
There is a roslyn analyser I want to make to detect bad usages like this but I couldn't be bothered to work much on it for now, my game is moving slow enough as it is ^^"...

**Comment by prime31** [comment]
I was just thinking the same thing. That I can add a simple check for any Type used in a filter and make sure no set/removed are called in the System loop.

I haven’t added EntityRecorder yet to my rig so this is the perfect opportunity to add it and go back and fix all my hacky Systems that we’re waiting for it!

**Comment by prime31** [comment]
EntityCommandRecorder fixed the issue (duh, my bad on this one!). Now I just have to just wire it up to my system scheduler to make everything happen automatically.

Looking at the code it appears that `Execute` calls `Clear` which resets the memory offset and also seems to squash the _lockObject if the buffer is resizeable. So, if I am following the code correctly this could happen:

- create expandable Recorder (zero param constructor)
- run some commands
- call `Execute` which runs the commands and then calls `Clear` which sees that the byte[] is expandable and wipes the `_lockObject`
- next frame of game...
- start using Recorder
- now we have no _lockObject so a (very) rare case might occur where the byte[] needs to be expanded while we are reading/writing

Is the point of the `Clear` command so that we can reuse the Recorders? If so and I am following along with the code correctly _lockObject shouldnt be disposed except in Dispose.

**Comment by Doraku** [comment]
The _lockObject is only disposed if the inner buffer has reached the max capacity
https://github.com/Doraku/DefaultEcs/blob/e2f8b79be6bca7e03f32ba67f6cdc638bb4d6f84/source/DefaultEcs/Command/EntityCommandRecorder.cs#L199
so at this point the recorder is no longer expandable. This is just a small optimisation to no longer take the read lock once we are at max capacity. If you are using the parameter less constructor, the max capacity is int.MaxValue so this probably will never happen and _lockObject will stay alive.

**Comment by prime31** [comment]
Ahh, yes. Good point. The chances of hitting that are zero when using the parameter-less constructor. I'll go forward with reusing a single EntityCommandRecorder per System then and see how it goes.
