### ISSUE TITLE
optimize component memory layout during runtime

### ISSUE THREAD

**Issue by Doraku** [Doraku/DefaultEcs#40]
As entities and components are added/removed, the layout in memory may not be in the order of ids since last element takes the place of removed item.
It could be interesting to allow the sorting of the memory through the api to optimize the layout (for example when presenting a frame ect...).
Something like this?
```
public class World
{
    // completely reorder layout to be optimized
    public void Optimize();
    // reorder layout as long as a cancellation is not requested
    public void Optimize(CancellationToken token);
}
```

**Comment by prime31** [comment]
Or you could go *CRAZY* and do the archetype/prototype memory layout like [Flecs](https://github.com/SanderMertens/flecs) and Unity do. But I wouldnt suggest that route, it's not fun at all to manage.

**Comment by Doraku** [comment]
I have read some stuff about that, if I ever do archetype it would not probably be before a v2 x) Sorting internal arrays will have to do for now!

**Comment by prime31** [comment]
Don’t even try it with C# ever! You have to switch to totally unmanaged code to be able to move things around. Might as well just use Flecs and write some C at that point.
