### ISSUE TITLE
Component change detection

### ISSUE THREAD

**Issue by RomanZhu** [Doraku/DefaultEcs#41]
Hi

Is it possible to detect when the component has changed?
This is important as it greatly simplifies gameplay logic.

**Comment by Doraku** [comment]
Hello, I guess you want to be able to react to component modifications with some kind of filter? This poses quite a challenge with the current api/implementation since Entity.Get<T>() returns a ref to the component so you can edit part of it without a full copy and the need to call Entity.Set<T>(T newValue).
Enforcing the Set method would cost too much perf wise and having both with only the Set method sending a notification would be confusing to me.

If your goal is to process complex calculation on an entity only if a component part of the inputs has changed maybe you can change the logic by using a flag component to tell when the system should run on the entity?

**Comment by RomanZhu** [comment]
In Entitas it works exactly like this. If you use Add*/Replace*, then reactive systems who looks for that component will be triggered, but if you change it without that API, for example, like this `entity.position = new Vector();`, then reactive systems won't be triggered. 

Then I would have thousands of tags :)

**Comment by Doraku** [comment]
This would probably go hand in hand with #36. I have been wary of adding reactive event point of entry in the api. I'm close to go with it, indeed not having to declare a flag for everything is a strong argument ^^", I'll try to tinker on this a little bit.

**Comment by RomanZhu** [comment]
Another important thing is those *reactions* should be handled in exactly the order in which systems are executed. What I mean by that is:
https://github.com/SanderMertens/flecs/issues/38

**Comment by Doraku** [comment]
Just a thought after sleeping, you can already mimic this behavior with a custom message you could publish after setting/changing the component on the world (this is basically what would happen anyway).
Still adding reactive capacities directly is worth exploring.

**Comment by RomanZhu** [comment]
Receivers of such message will be triggered at the same time when you publish that message? Or they will be triggered when it's their turn to execute?

**Comment by Doraku** [comment]
They will be triggered synchronously with the publish. Since I don't want to enforce the use of my implementation of systems I couldn't tie it to the update logic.
I have a somewhat close case to your linked issue in flecs in my game: bullets collision.
When a collision occurs the callback to the message simply store it in a thread safe collection (I use a custom circular buffer for this but anything would do) to store them so they can be checked later on. As multiple bullets can collide with the same entity (which can be destroyed in the same frame by a previous bullet) I have to check them sequentially but it's more interesting to get all the possible collisions with multi-threading.
You could easily create a collection type to hold received messages, and on the update of your system process them for real as needed.

**Comment by RomanZhu** [comment]
Thanks, that's what entitas does behind the scenes :D

**Comment by Doraku** [comment]
I guess they also did not found a cleverer way to do it ^^
It should be possible to create some kind of DelayedPublisher type implementing IPublisher with an extra Process method, using an inner IPublisher to receive and store messages, and invoke the real callbacks when Process is called to hide all this mechanism. But I am not sure it has its place in the framework as this is quite specific.

**Comment by RomanZhu** [comment]
The way it's implemented in Entitas is like this:
There are 2 event types exist: replaced, removed

The system creates collector and set's what component types and what event types it is looking for.
That collector subscribes to global events and if the required component was invoked with required event type, then the collector will add that entity into HashSet.
When it's system's turn to execute, then it gives you all entities from HashSet.

Those events are triggered only when you do Add/Set/RemoveComponent
I guess it won't be that hard to implement by myself :v

**Comment by Doraku** [comment]
I'm starting to think of adding some WithNew<>, WithChanged<> (for explicit entity.Set<>) and WithRemoved<> (for newly removed component) methods on EntitySetBuilder.
Adding those would not be the problem but they raise a couple of issues:
- For the newly removed component, that mean this happen after the component has been removed so when you get the entity in the set you can't see the old value. I don't know if this is ok
- It misses a method to clean up the EntitySet of those "react" entities, CleanReact? Maybe then add "react" in the name of the builder methods for those filters
- Is it even a good idea to mix react and basic subscription in the same EntitySet? This has the benefit of not changing the api for systems and existing code
- What happen if you have a filter with WithNew and do Set and Remove on an entity? I guess if it didn't had the opportunity to process its entities it shouldn't appear in the set?

Typing this so I don't forget about it after work :p

**Comment by RomanZhu** [comment]
1) Yep, that is how it works in entitas
2-3) In entitas there is a difference between regular systems AND reactive systems. Maybe you could create a new system type too?
4) In Entitas it's "solved" by having `Filter` method in reactive systems. Each collected entity will be sent into that method and if it returns `true`, then that entity will be given to the user. `Filter` method is implemented by the user, so he can check component existence if he actually needs it.
But personally, I could live without that method. Automatically filtering of collected entities seems good.

**Comment by Doraku** [comment]
Having two different systems doing essentially the same feel like a waste to me. Maybe two different types of EntitySet hum...

That filter method is easy enough to replicate by overriding `protected virtual void Update(T state, ReadOnlySpan<Entity> entities)` and doing the check here. Only difference is that the filtering will be split across threads if using a SystemRunner while in Entitas, this is done single threaded before the split I believe.

**Comment by RomanZhu** [comment]
Hm, I see how we can use EntitySet as a filter
`.With<A>().WithNone<B>().WithAdded<A>().WithChanged<A>()`
That way system could filter using those regular `.With` `.Without` when it is about to execute

That would be perfect

**Comment by Doraku** [comment]
I am closing on a satisfying api to me but still have some points I am not sure would make sens for the majority.

`EntitySetBuilder.WhenAdded<T>()`
`EntitySetBuilder.WhenChanged<T>()`
`EntitySetBuilder.WhenRemoved<T>()`

Those would be the added methods, calling one of them when creating an EntitySet would, once build, return a special EntitySet you can clear of its entities once processed (still need to work on that). 

- `WhenAdded<T>()` the set would react to enabled entities on which a component T is set for the first time or re-enabled after being disabled. Disabled entities will not appear in there, but enabling an entity with a component T will be picked up. If T is removed/disabled from the entity, it will disappear from the set.
- `WhenChanged<T>` only enabled entities on which a component T is explicitly set (`Entity.Set<T>`) will appear. Disabled entities will not appear in there. Also in the case a component is shared between multiple entities (`entity1.Set<T>(); entity2.SetSameAs<T>(entity1);`), only the entity on which the second `Set<T>` is done will appear, sharing entities will not be present in the EntitySet even though their component has also changed. If T is removed/disabled from the entity, it will disappear from the set.
- `WhenRemoved<T>` only enabled entities on which the component T is removed or disabled will be in there. if T is added/enabled from the entity, it will disappear from the set.

You can mix those rules with the existing ones: `With<T1>().Without<T2>().WhenAdded<T3>()` would get you only entities with a T1 component and without a T2 component, on which a component T3 is added. In the case of an entity with a T3, on which you later set a T1, it will also appear.
`WhenAdded<T1>().WhenAdded<T2>()` will pick up entities on which either T1 or T2 is enabled/set for the first time. 
`WhenAdded<T>().WhenRemoved<T>()` will pick up nothing
`WhenAdded<T>().WhenChanged<T>()` is the same as `WhenChanged<T>()`

**Comment by Doraku** [comment]
Finally done, in the end I went with stronger rules:

`WhenAdded<T>` only trigger for enabled entities when you add/enable T, not the entity itself
`WhenChanged<T>` only trigger for a change, it does not include WhenAdded
`WhenRemoved<T>` only trigger for enabled entities when you remove/disable T

A method `Complete` has been added on `EntitySet` to clear it of its entities once processed (this is automatically done if you use `AEntitySystem`). I'll try to see if I can change some of my game systems to be reactive to check that everything works fine, a new version should follow soon after.

Maybe later I'll add the `Any` variants, but for now I'll close this :)
