### ISSUE TITLE
Visualization of world state

### ISSUE THREAD

**Issue by RomanZhu** [Doraku/DefaultEcs#43]
What are your thoughts about the visualization of the world state?

For example, in Entitas (In Unity) we have the ability to see all executing systems and all entities with all components and the ability to add/change/remove components

Maybe you have implemented something for XNA already?

**Comment by Doraku** [comment]
I have added custom debug views (DefaultEcs/Technical/Debug, sorry on the phone so hard to link correctly) for the important types to enhanced the debugging so you can more easily see the state of everything.
I have yet to create a release with this change but I think this handle the visualization part?

**Comment by RomanZhu** [comment]
Yep, it will make it easy to write inspectors
