### ISSUE TITLE
Find entity by component value

### ISSUE THREAD

**Issue by RomanZhu** [Doraku/DefaultEcs#45]
Hi :D

There is one more feature I used all the time in Entitas https://github.com/mzaks/EntitasCookBook/blob/master/chapters/1_ingredients/106_index.md

TLDR: Have an API to find an entity OR entities with a specified component value

Use cases:
- Networking: A lot of times you need to modify entity with specific Id.
- Grid-based games: Get entity standing on a specific position (under mouse cursor, near explosion,  etc)

What do you think about it?
It's possible to get away with messages, yes.

**Comment by Doraku** [comment]
Hum since I added the "When" variant I guess you could create your own Dictionary<TComponent, Entity> or any other collection as the TComponent values change.
I like the idea of an Indexed set, it may deserves to be in the framework directly.

**Comment by RomanZhu** [comment]
There is the problem with `When` 
I guess you won't add system which will put entities into Set after each system which could change entities?

**Comment by Doraku** [comment]
What do you mean by a problem with When?
I don't really understand what you mean with your second sentence. EntitySet currently only serve as a selection of entities based on composition (and event) to be fully itterated on by systems. To identify entities or a single entity by a component value is something else as their purpose is not to be fully itterated over but simply give a quick access on a subgroup of entities or a single entity based on values, not composition. There is multiple representation possible (hashmap/dictionary,  octotree,...)  each with their own purpose (id access, range of position to limit collision detection). Maybe I could add an api to help implement such a set generic enough so it is possible to select your own representation.

**Comment by RomanZhu** [comment]
Systems with "When" are triggered in the order of system execution, right?
They are not immediate. If there is a way to get an immediate callback before/after component change please let me know.

For example, we have a situation like this:
We have Dictionary<Vector2Int, Entity> in the controller.
- System A changes the `Position` component on an entity.
- System A tried to lookup the entity at that new position, but Dictionary is not yet updated with changes.
- System C should remove old `Position` key in the dictionary (how it would know old value?) and add a new key with new `Position` value

**Comment by Doraku** [comment]
Ah indeed it is always for defered execution, but you do have EntityAdded and EntityRemoved event on EntitySet to add direct execition logic as the set change if you want, maybe you could use that?
