### ISSUE TITLE
Generation ID for entity ?

### ISSUE THREAD

**Issue by RUSshy** [Doraku/DefaultEcs#47]
Hi

I see you reuse ID, but there is no way to differentiate Entity

In other ECS libs, they add a specific field (generation/version), it is incrementated for each reuse of the entity ID

**Comment by Doraku** [comment]
Yes, since an entity is already 2 int (one for the static arrays index and one for the real index) I didn't want to make it any heavier. This does mean you need to be careful when storing entities outside of EntitySet but I think the tradeoff for memory and performance is worth it, at least I haven't encountered a problem because of this yet. I may be a bad reference for this though since I am the author ^^"

**Comment by dzmitry-lahoda** [comment]
seems like part of int value (e.g. up to 1M value bit) could be the way to go. And do cycle instead of pop-push. so avoid reuse and avoid large memory usage.

**Comment by Doraku** [comment]
So I finally took some time to look at the "backlog" so to speak :p
On this branch https://github.com/Doraku/DefaultEcs/tree/EntityVersion I reduced WorldId int to a short (hopefully you would not create more than 32767 World at the same times!), leaving me the size to add an other short for the Entity version (thus keeping its original size). The IsAlive property of Entity correctly take this into account. I am not to sure to add this check in other Entity's methods as I think most use cases would be to have some `#if DEBUG` or `[Conditional("DEBUG")]` decorated method checking this flag to throw an exception in users code to help find problems in the development phase and remove them in release.

**Comment by RUSshy** [comment]
https://github.com/Doraku/DefaultEcs/blob/EntityVersion/source/DefaultEcs/Entity.cs#L387

Should also compare version no?

**Comment by Doraku** [comment]
That was definitely a miss on my part for the Version.
I've added directly both operators on master, no reason for them not to be there. Thanks for bringing it up.

**Comment by volundmush** [comment]
Consider creating an IdComponent that holds an int or Guid or string or some other value you can use as a unique key for the Entity, and then when you create an Entity you assign it one. a simple Dictionary<keychosen, Entity> is a quick and straightforward way to index them. Build on this idea for better performance and style as you please.
