### ISSUE TITLE
Boxing in loop?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Doraku/DefaultEcs#48]
Look seems to be hot and with boxing. Is it possible to avoid? If not - please add comment why not.

https://github.com/Doraku/DefaultEcs/blob/f283587de37ccf6099d0c7f0ceef048959756243/source/DefaultEcs/System/SystemRunner.cs#L54

**Comment by Doraku** [comment]
This is actually just boxed once at the creation of the SystemRunner when it initializes its worker task/thread, not anymore in the hot path. The main goal of this class is to avoid memory allocation after the initialization for multi threading so I hope I didn't miss this target ^^".
I have been thinking of adding an interface to this class so it is possible to change the implementation of multi threading execution but haven't taken the time to do it yet btw.
