### ISSUE TITLE
ValueTask usage?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Doraku/DefaultEcs#49]
I see Tasks are used. May be replace with ValueTask?

https://github.com/Doraku/DefaultEcs/blob/f283587de37ccf6099d0c7f0ceef048959756243/source/DefaultEcs/System/SystemRunner.cs#L44

**Comment by Doraku** [comment]
ValueTask will be available from netstandard 2.1 I think while DefaultEcs try to target as low as 1.3. Also using ValueTask does not make much sence, those tasks are only really just thread abstraction the way I am creating them, they run as long as the SystemRunner exist (normaly the full game duration) and you only await them when disposing the runner.

**Comment by dzmitry-lahoda** [comment]
I guess possible preferable approach for ECS will be `async ValueTask` - i.e. direct modelling of background systems. So there is more control. So async background systems are not hidden, but explicitly modeled. So just guess. May be not.

**Comment by dzmitry-lahoda** [comment]
Like IEnumerable and IAsyncEnumerable

And you may provide ValueTask from network io, from io, from game look (unity game look is async), from thead pool, from custom pool-list(fibers). I.e. system is async by interface and tech to do stuff in background is not ECS deal.
