### ISSUE TITLE
Consider bit level API for more serious game.

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Doraku/DefaultEcs#54]
https://github.com/Doraku/DefaultEcs/blob/f283587de37ccf6099d0c7f0ceef048959756243/source/DefaultEcs/Serialization/ISerializer.cs#L23

https://github.com/dzmitry-lahoda/NetStack/blob/master/Assets/Scripts/src/NetStack.Serialization/IRawWriter.cs

https://github.com/dzmitry-lahoda/NetStack/blob/master/Assets/Scripts/src/NetStack.Serialization/IRawReader.cs

**Comment by dzmitry-lahoda** [comment]
If previous state of world available, consider API with previous world. Essentially I guess next gen ECS will(must) provide multi world out of box (i.e. any update is not in place-immediate, but for some count of frames old world is accesible).

**Comment by Doraku** [comment]
Hum the serializers have static generic methods for object direct serialization which call a delegate specific for the processed type already, you only really pay the delegate dispatch which is not that much (and with static delegate could completely disapear). If anything the interface really need something for #32 but I am still not sure how far I want to go with this feature, basic creation or possibility to give dynamic variable to the factory.
As for the state history, like I said in #55, while I get this would be neat, I am still unsure how to do it without much performance loss.

**Comment by dzmitry-lahoda** [comment]
Fast paced games store state (e.g. https://github.com/Unity-Technologies/FPSSample) of  components  using bit packing. same code can be used to store replays and send data over network. without bit access data is HUGE. `Stream` has no bit API. So it is not very industrial way to serialize. Could be better to wrap into some interface. 

Having access to previous world allows to do delta-diff (send-store only changed data) - reduced data 2-5 times.

**Comment by Doraku** [comment]
I was hoping for the inclusion of the span overload on Stream in netstandard 2.1 to accelerate things up. But yeah I guess a stream might not be appropriate to every situation.

**Comment by Doraku** [comment]
Looking back on this old issue, while Stream does not provide an API to do bit operations you could use a wrapper internally to expose such features for a custom serializer (using some king of buffer to do so before delegating it back to the Stream). Making a serializer was a crazy enough endeavor, as I am not going to go this extra mile I am closing this ^^".
