### ISSUE TITLE
Can't add multiple ManagedResources to a single entity for loading of same resource

### ISSUE THREAD

**Issue by MarkWilds** [Doraku/DefaultEcs#66]
When for example needing multiple textures on a single entity:
entity.Set(new ManagedResource<string, Texture2D>("t1));
entity.Set(new ManagedResource<string, Texture2D>("t2"));

It will only handle one with a ResourceManager.

**Comment by Doraku** [comment]
So it is a little cumbersome but this is handled by setting a ManagedResource<string[], Texture2D> and in your ResourceManager you will receive one call for each info loaded, after that it is up to you to do what you want depending of the value of info.

It is stated in the [readme](https://github.com/Doraku/DefaultEcs#resource) but I should add an example to make it clearer :/

**Comment by MarkWilds** [comment]
Thanks, somehow read over it

**Comment by MarkWilds** [comment]
But one thing, now I see that My AResourceManager<string, Texture2D> isnt doing anything anymore.
And if I change my string to string[] it feels weird as I need to change all my methods in the conrete implementation and Load(..) gets weird.

**Comment by Doraku** [comment]
You should not have to change anything in your implementation of AResourceManager<string, Texture2D>, maybe there is a bug I missed. I will check quickly.

**Comment by Doraku** [comment]
It definitly isn't working as expected! It do not check the array variant on existing entities when you call Manage. You can work around it by calling Manage on your world before setting the components on your entities, I will fix this thanks for bringing it up and sorry for the bug ^^"

**Comment by MarkWilds** [comment]
Can I fix it and make a PR if you want?

**Comment by Doraku** [comment]
Sure, I won't be able to do it until tomorow.

**Comment by Doraku** [comment]
Thx for the pr, maybe I will create a release this week end for nuget but you can use the preview package from [github](https://github.com/Doraku/DefaultEcs/packages/26448) (should be there any minute if all is ok ^^) in the meantime :)
