### ISSUE TITLE
Queue messages?

### ISSUE THREAD

**Issue by MarkWilds** [Doraku/DefaultEcs#70]
Is there a way to have queued messages? if not do you think this would be a good Idea?
I would like to be able to publish a message that gets handled at the start of a frame instead of instant.

**Comment by Doraku** [comment]
Nothing built in to handle that, but you could easily do it two way:
- Create a IPiblisher wrapper, storing message on Publish, and when a specific method is called, you process all of them for real
- Create a queue on the subscription method you want to be delayed to store received messages, and handle them when you want.

I am actually using the second option in my game and the question to include it here has been on my mind for a while (#26) but I still can't decide if it has its place here. The pub/sub is central to the internal of DefaultEcs but the public exposition is pretty light and for now I am more on the side that this responsability should not be on the lib itself.

**Comment by MarkWilds** [comment]
Can you show some code what you mean with option 2?
And is #26 related to this? Entity pools?

**Comment by Doraku** [comment]
```
internal sealed class BulletSystem : ISystem<float>
{
        private readonly RingBuffer<NewBulletMessage> _newBullets;

        public BulletSystem(World world, Configuration configuration)
        {
            _newBullets = new RingBuffer<NewBulletMessage>(100);

            _subscription = world.Subscribe(this);
        }

        [Subscribe]
        private void On(in NewBulletMessage message) => _newBullets.Add(message);

        public bool IsEnabled { get; set; } = true;

        public void Update(float state)
        {
            if (IsEnabled)
            {
                foreach (NewBulletMessage message in _newBullets)
                {
                    // setup bullet
                }
            }
        }
}
```
This is a simplified version of the bullet system of my shooter. Bullet can be generated by multiple sources (and in parallel) so they relay the actual creation at a determined step by sending a specific message.
I cited #26 because I am using custom collections for my need (multi writer thread safe, single reader not thread safe for the RingBuffer here) but you can use anything really.

Problem with this solution is that it is specific to a type of message. I don't know how general you need it.

Maybe I could create an extension method to make it more easily setup-able
```
public class DefferedSubscription<T> : IDisposable
{
    // contains a list of T and Execute actually call action on them
    public void Execute();
}

public static DefferedSubscription<T> DefferedSubscribe(this IPublisher publisher, ActionIn<T> action, int maxMessageCount);
```

**Comment by MarkWilds** [comment]
I like how you solve this problem and defer events by using a system to collect the events so that you can decide when to execute them.

You should make examples of these questions! A faq.

**Comment by Doraku** [comment]
That's definitely something I should do, the readme overview is kinda too general and it's not really the place for specific explanations.
