### ISSUE TITLE
Best practice for setting up entity dependencies in a system?

### ISSUE THREAD

**Issue by MarkWilds** [Doraku/DefaultEcs#72]
Do you mind me asking question here? as there is no official chat/other communication channel.

Say I have a maprendering system that is dependant upon a camera entity (only one currently).
What would be the best way to handle this?

Currently I do:
`            cameraEntitySet = world.GetEntities()
                .With(typeof(Transform2D))
                .With(typeof(Camera))
                .Build();`
In my constructor and:

`            var camera = cameraEntitySet.GetEntities()[0];`
In my update.

**Comment by Doraku** [comment]
No problem :)
I am no authority on this subject but it makes sense to me, I am actually doing the same in some of my systems
```
    // don't care about collision between enemies and collision between allies
    [With(typeof(Enemy), typeof(CollisionBox))]
    public sealed class CollisionSystem : AEntitySystem<float>
    {
        private readonly EntitySet _allies;

        public CollisionSystem(World world, SystemRunner<float> runner)
            : base(world, runner)
        {
            _allies = world.GetEntities().With<Ally>().With<CollisionBox>().Build();
        }

        protected override void Update(float state, ReadOnlySpan<Entity> entities)
        {
            foreach (ref readonly Entity ally in _allies.GetEntities())
            {
                foreach (ref readonly Entity entityin entities)
                {
                    if (entity.Get<CollisionBox>().Intersects(ally.Get<CollisionBox>()))
                    {
                        ...
                    }
                }
            }
        }
    }
```
That way your systems stays dynamic to your world changes (in my case what if a new player join, player dies and respawn? already taken care of!). Just if some of your systems need the same EntitySet configuration, you should try to share the same instance between them so you don't have duplicate (I wanted to handle that automatically behind the scene but didn't do it in the end).

**Comment by MarkWilds** [comment]
Thanks!
