### ISSUE TITLE
Feature request: Unsubscribe? 

### ISSUE THREAD

**Issue by neronmoon** [Doraku/DefaultEcs#86]
Hey!
How can I can subscribe to World's events, but cannot unsubscribe! That's feels strange :)

**Comment by Doraku** [comment]
You mean the [`Subscribe<>`](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/DefaultEcs-World-Subscribe-T-(DefaultEcs-ActionIn-T-).md) method? It returns an `IDisposable`, to unsubscribe simply dispose it.

**Comment by Doraku** [comment]
I guess this is what you wanted ^^"? if not feel free to reopen the issue.
