### ISSUE TITLE
Fixe AoT compilation attribute usage and EntityRecord.Set for unmanaged type

### ISSUE THREAD

**Issue by Doraku** [Doraku/DefaultEcs#87]
Currently it is impossible to use `SubscribeAttribute` and the `ComponentAttribute` family in AoT compilation because of reflection usage (DefaultEcs.Serialization also does not work because of the usage of `System.Reflection.Emit` but that's for an other time). Setting an unmanaged type on an EntityRecord also doesn't work because of a special generic type used internally which need to be discovered at runtime.

Known work around is to have a static usage in code of the generic methods so the code is generated.

```
    public static class AoTHelper
    {
        public static void RegisterComponent<T>()
        {
            new EntitySetBuilder(default, default)
                .With<T>().WithEither<T>().Or<T>().WithEither<T>().With<T>()
                .Without<T>().WithoutEither<T>().Or<T>().WithoutEither<T>().Without<T>()
                .WhenAdded<T>().WhenAddedEither<T>().Or<T>().WhenAddedEither<T>().WhenAdded<T>()
                .WhenChanged<T>().WhenChangedEither<T>().Or<T>().WhenChangedEither<T>().WhenChanged<T>()
                .WhenRemoved<T>().WhenRemovedEither<T>().Or<T>().WhenRemovedEither<T>().WhenRemoved<T>();
        }

        public static void RegisterUnmanagedComponent<T>()
            where T : unmanaged
        {
            RegisterComponent<T>();

            unsafe
            {
                UnmanagedComponentCommand<T>.WriteComponent(default, default, default);
                UnmanagedComponentCommand<T>.SetComponent(default, default, default);
            }
        }
    }
```

This type would give access to the internal type methods which need to be known at compilation, tested on CoreRt AoT and it fixes the `ComponentAttribute` family and unmanaged type `EntityRecord.Set`. Wouldn't be against some help to test it for mono AoT and unity IL2CPP.

`SubscribeAttribute` is a little more problematic because it uses extension methods on the `IPublisher` interface. Tried this:
```
        public static void RegisterMessage<T>()
        {
            default(World)?.Subscribe(new ActionIn<T>((in T _) => { }));
        }
```
but I still get a `System.Reflection.MissingRuntimeArtifactException`.

Next step would be to create a pre build target so all the component/message used can be automatically registered in a dummy type using roslyn or something to get all `SubscribeAttribute`, `ComponentAttribute` and `EntityRecord.Set<>` usages, so users don't even have to think about this...

linked to #51

**Comment by Doraku** [comment]
5857f2078ae8042ca3f3ead574f7c4871bd75e61 for `ComponentAttribute` and `EntityRecord.Set<>`

**Comment by Doraku** [comment]
14bcb8959fe22b08997e4dbba355cdff89bd3846 for SubscribeAttribute

**Comment by Doraku** [comment]
awaiting https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/ goodness for the next step

**Comment by neronmoon** [comment]
Hey!

I've been building my unity project for IOS and faced an issue, that looks similar.
```
IL2CPP error for method 'System.Void DefaultEcs.Entity::Set(T&)' in assembly '*****/Temp/StagingArea/Data/Managed/DefaultEcs.dll'
Additional information: Failed to resolve type reference
```

Am I correct, that this is same issue? Or I should dig the other ways?

**Comment by Doraku** [comment]
Hoy, that definitely seems related, but I wouldn't expect it to fail on the `Entity.Set` method since the generic variants are called explicitly by your usage so it should generate the typed generic code :/ or maybe ILCPP doesn't work the way I think it would, does it needs the sources of the generic code to generate the types variant or does that also works with generic types of referenced assembly?

**Comment by Doraku** [comment]
I tried to look a little more into it but with no IOS platform to test this is just blind speculation. Maybe the error has to do with the stripping of byte code done by the IL2CPP process? Apparently it is possible to state that you want to keep all the byte code of a referenced assembly, see [here](https://docs.unity3d.com/Manual/ManagedCodeStripping.html) with something like this:
```
<assembly fullname="DefaultEcs" preserve="all"/>
```

**Comment by Doraku** [comment]
Took me long enough but I finally installed and played around with Unity. It seems IL2CPP doesn't like generic in parameter with default value.
@neronmoon not sure if this still interest you but I just pushed version 0.15.1 which remove the default value parameters and the project build successfully. I have other stuff to test before shouting victory but it's coming along nicely :)

**Comment by Doraku** [comment]
Tested on Unity 2020.2.3f1, IL2CPP windows, EntityCommandRecorder and component attribute usage for system work correctly when using `AoTHelper` to ensure generic method declaration.
