### ISSUE TITLE
AResourceManager load usage

### ISSUE THREAD

**Issue by jnoyola** [Doraku/DefaultEcs#91]
I'm trying to find the proper way to use `AResourceManager`, and I don't see too many examples so I thought I'd see if you can help.

The example in the readme shows you can load a `Texture2D` and the manager can assign it to the `DrawInfo` component (which I believe it's just assuming any entity with a `ManagedResource<string, Texture2D>` will have). But this example already breaks down when you show how to load multiple resources of the same type. The `circle.png` will presumably overwrite `square.png` in the entity's `DrawInfo`.

So how would this work in a real-world scenario? Let's say you need a texture for a character, and a texture for his footprints. The manager wouldn't know where to put each. You could create a separate manager for each kind of `Texture2D` (e.g. a `CharacterTextureManager` and `FootprintTextureManager`). These would be mostly identical though, except for the field, or maybe component, that you're setting. I thought you could try specifying the destination along with the texture name in `TInfo`, but then you'd need reflection or something to set it.

Is there a good way to specify which component or field to load resources into so that you can reuse resource managers? Hopefully the question makes sense.

**Comment by Doraku** [comment]
Yes you can put more information into the TInfo so you know how to use your TResource and pass a `ManagedResource<TInfo[], TResource>` so your entity can hold multiple resource (note the array on TInfo):
```
public enum TextureType
{
    Character,
    Footprint,
    ...
}

public readonly struct TextureInfo
{
    public readonly TextureType Type;
    public readonly string File;

    public TextureInfo(TextureType type, string file) { ... }

    // maybe override Equals and GetHashCode to only use File, so the TextureManager do not load a single texture multiple times if it is used as multiple TextureTypes
}

public class TextureManager : AResourceManager<TextureInfo, Texture2D>
{
    ...
    protected override void OnResourceLoaded(in Entity entity, TextureInfo info, Texture2D resource)
    {
        switch (info.Type)
        {
            ...
        }
    }
    ...
}

entity.Set(ManagedResource<Texture2D>.Create(
    new TextureInfo(TextureType.Character, "c.png"),
    new TextureInfo(TextureType.Footprint, "fp.png"));
// or equivalent without the extension helper
entity.Set(new ManagedResource<TextureInfo[], Texture2D>(new []
{
    new TextureInfo(TextureType.Character, "c.png"),
    new TextureInfo(TextureType.Footprint, "fp.png")
});
```
Beside the verbosity, one limitation is that you can't change juste one TInfo in the array, you have to change the whole ManagedResource<TInfo[], TResource> but I don't think this should happen too much when your game is properly running (maybe in character select screen where you can customize your appearance?) and depending on what you are doing with your TResource you have to be careful of the order you are setting things (like in my example setting it on an expected component `DrawInfo`).

**Comment by jnoyola** [comment]
Oh, looks like you just commented at the same time. Let me finish posting this and then I'll read yours.


I came up with the following, where `TInfo` is a combination of the resource ID and an output selector, but it's kind of ugly. It might be cleaner to just make an enum of uses for each resource type, let `TInfo` be `(string, Texture2DKind)`, and put a switch-case inside the manager.

```csharp
    class ContentResourceManager<TComponentType, TContentType> : AResourceManager<(string, ContentResourceManager<TComponentType, TContentType>.OutputSelector), TContentType>
        where TComponentType : struct
        where TContentType : IDisposable
    {
        public delegate ref TContentType OutputSelector(ref TComponentType component);

        private readonly ContentManager contentManager;

        public ContentResourceManager(ContentManager contentManager)
        {
            this.contentManager = contentManager;
        }

        protected override TContentType Load((string, OutputSelector) info) => contentManager.Load<TContentType>(info.Item1);

        protected override void OnResourceLoaded(in Entity entity, (string, OutputSelector) info, TContentType resource)
        {
            var (_, outputSelector) = info;
            ref var outputRef = ref outputSelector(ref entity.Get<TComponentType>());
            outputRef = resource;
        }
    }
```
With a custom helper class to help with type inferencing, usage looks like this:
```csharp

entity.Set(
    MyManagedResource<Texture2D>.Create(
        ("character.png", (ref Component c) => ref c.CharacterTexture),
        ("footprint.png", (ref Component c) => ref c.FootprintTexture)));
```

**Comment by Doraku** [comment]
No I think it looks good, I was actually going to propose a solution like that at first :D Only problem you could have is if you want to create an editor for your entities, creating a OutputSelector and serializing/deserializing it might be a pain which is why I ended up with the enum, after all I added those type to solve the problem of serialization/deserialization of resource as component so TInfo should be serializable ^^
But if you are only using it in code it's better your way, just my personal taste but I would create a proper type to hold the string and OutputSelector, since you can't override the Equals/GetHashCode on ValueType.

**Comment by jnoyola** [comment]
Well I think those two options satisfy my question. I like the idea of it being serializable for saving and loading in the future.

Is there a need to override `Equals` and `GetHashCode` on `TInfo`? Is that how it determines if multiple entities are using the same resource?

**Comment by Doraku** [comment]
Yeah internally `AResourceManager<TInfo, TResource>` use a dictionary
https://github.com/Doraku/DefaultEcs/blob/566186706360454e483137b9aaea3a7682da533b/source/DefaultEcs/Resource/AResourceManager.cs#L54
so it only load your resource once and share it between your entities, even across different World instances (and is thread safe).
The `ContentManager` of Monogame do the same I think but you can't remove a single loaded resource, you have to unload the full `ContentManager` while `AResourceManager<TInfo, TResource>` count the number of reference `TInfo` on the resource  and automatically dispose it for you once no entities use it anymore (you would probably have a crash with this code if you create one entity using a resource, dispose the entity and create a new one using the same resource because `AResourceManager<TInfo, TResource>` will dispose the texture the first time but `ContentManager` will happily give you back the disposed texture the second time ^^")

**Comment by jnoyola** [comment]
Ah that's a good point about MonoGame. I had forgotten about that. So how would you recommend using resource managers with MonoGame? The options I can think of are:
* Don't.
* Bypass `ContentManager` and use `AResourceManger` directly with the readers and loaders.
* Wrap content types in a generic `IDisposable` that doesn't actually dispose so that if `DefaultEcs` can't dispose content, and use `ContentManager.Unload()` to dispose everything.

**Comment by Doraku** [comment]
The `ContentManager` gave it away, I use MonoGame too ^^ so obviously I am not going to say to not use their great work hehe
Personally I bypass their ContentManager, most of their resource types (Texture2D, Sound, ...) have some static `FromFile` or `FromStream` to create instance for you, so the code of the managers is not much different. While my game can change scenes, each with its own World and systems, their is only one instance of each manager so I can reuse the already loaded assets between them and disposing a scene will also dispose its World and the resources which are not used by the new one.
Creating a wrapper would work but I feel sorry to make you do that... I am starting to doubt forcing `TResource` to be disposable, maybe I should remove this restriction and make a virtual `Remove` method which dispose the resource if it is an `IDisposable` by default, that way people would be able to override it to change the behavior if needed. What do you think?

**Comment by jnoyola** [comment]
Allowing content to choose whether or not to be `IDisposable` sounds like a reasonable compromise, but I'm leaning towards bypassing the `ContentManager` too, since it sounds like a lot of the seasoned MonoGame pros do that as well. And if you're saying it's not very difficult and `DefaultEcs` handles the lifecycle better, then that sounds like enough reasons.

**Comment by Doraku** [comment]
Oh like when an app is put in the background and then need to reload some asset when it is active again? I didn't know that, I never tried this case when testing my game on my phone. I will keep this in mind!

**Comment by Doraku** [comment]
0c3a400c64a1bfb21eb7dc469dfc764f5c7350b6 I went ahead and removed the IDisposable constraint on TResource and added a virtual Unload method. It was kind of stupid of me to force that anyway, you could have resources which are not IDisposable but take a long time to load for example.

**Comment by jnoyola** [comment]
> I went ahead and removed the IDisposable constraint on TResource and added a virtual Unload method.

That's actually super helpful for both implementations! My new plan is to subclass the ContentManager with an `Unload<T>(string assetName)` that disposes it and removes it from the dictionary. Then I can override the `AResourceManager<>.Unload` to instead call `ContentManager.Unload(info.assetName)`.

Then, as long as your Worlds are linked to your ContentManagers 1-to-1, and you don't dispose a ContentManager while its World is still active, you shouldn't have to worry about the ContentManager passing you back a disposed piece of content. I think that solves all the problems, right? Or am I missing something?

When can we expect this update in a new NuGet version? 😀

**Comment by Doraku** [comment]
I believe you can even use a single ContentManager for all your Worlds with this, no problem comes to mind.
I will probably release this update later today or tomorrow ;)

**Comment by jnoyola** [comment]
If two worlds have entities with the same `ManagedResource`, then when one world releases all references, the `ContentManager` would Unload and Dispose the content, which would kill the other world's source for that resource as well. So I think you'd need one `ContentManager` per world if there's any chance of having resource overlap.

**Comment by Doraku** [comment]
no, if a resource is used by an other entity in an other world the `Unload` method of AResourceManager will not be called :) That was the whole point, so you don't have to reload everything between screen.

**Comment by jnoyola** [comment]
Ok cool! I thought reference counts were tracked in each world.

**Comment by Doraku** [comment]
Yeah you can call the [Manage](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/DefaultEcs-Resource-AResourceManager-TInfo_TResource--Manage(DefaultEcs-World).md) method on multiple `World`. so it should be easy to have a single manager instance for each resource type.
Note that this method return an `IDisposable` to cancel the subscriptions done on the `World` instance to receive its `ManagedResource<,>` events but if you dispose the `World` itself it will cleanup its used resource automatically. If you dispose this `IDisposable` returned by the `Manage` method before you dispose the `World` you could end up with resources that will never be unloaded until you dispose the manager itself though so be careful.

**Comment by Doraku** [comment]
If you need any more assistance don't hesitate to reopen this issue or create a new one, I will close it in the meantime ;)

**Comment by jnoyola** [comment]
I'm taking another pass over this, and I think I decided I want my cached resources tied to the lifecycle of a World, rather than long-living and tied to the lifecycle of my ContentManager. (Reason at the bottom)

Since the change to how `AResourceManager<>.Unload` works, this is actually super easy! The `ContentManager.Unload` method does two things: dispose if it's `IDisposable`, and remove it from the cache. As it turns out, `AResourceManager<>.Remove` now does exactly that! All we have to do now is bypass the `ContentManager` cache, and luckily there's a handy (protected) `ReadAsset` method that only reads and doesn't touch the cache. So my solution is to
1. subclass the `ContentManager` with a public `Read` method that exposes `ReadAsset`
2. make `AResourceManager<>.Load` call `ContentManager.Read`, and don't override the default `Unload`

<br/>
<br/>

Reason: This way I can tie memory _capacity_ to a World. For example, if you're using a BufferPool (a big chunk of pre-allocated memory from BepuPhysics), you can return blobs to free up _usable_ memory, but the memory _capacity_ doesn't get reset until you manually clear the pool. Now, instead of requiring the BufferPool to be long-living to hold my pieces of content that are long-living, I can clean it all up when I dispose my World so that I can easily free up RAM between levels

**Comment by jnoyola** [comment]
I have a request related to this. It looks like it's actually pretty easy to do this the "right" way by hooking into `ContentManager`'s `ReloadGraphicsAssets`, but it would require a small change. So the plan is to do the following:

1. Override `ContentManager`'s `ReloadGraphicsAssets` to trigger a reload on all the `AResourceManager`s.
2. `AResourceManager` has a reload method that loops over all of its resources and calls `Reload` for each asset (because the resource manager already has a map of their names and `existingValue`s).
3. `ContentManager` exposes a public `Reload` method that simply calls the protected `ReloadAsset`.

The whole thing would only take a dozen lines of code, but the tricky part is that my `AResourceManager` subclasses need access to the `_resources` map (and ideally the lock). Alternatively, maybe `AResourceManager` could have a method that takes an `Action<TInfo, TResource>` and runs it on every `KeyValuePair` in the dictionary. Could something like that be worked in?

If so, we get the advantages of lifecycle and memory management from `AResourceManager` while keeping the reading and reload hook from the `ContentManager`, which I think would be awesome.

**Comment by Doraku** [comment]
hum would exposing the `KeyValuePair<>` contained in `_resources`  either as a property of `AResourceManager<>` or directly making it implement `IEnumerable<KeyValuePair<>>` work for you? It feels more natural to me for `AResourceManager<>` to expose safely what it contains, adding a method with an `Action<>` seems like something too specific.

**Comment by jnoyola** [comment]
Yes, I'm open to those. Basically anything where I can access those pairs.

The end result will probably look something like this:

```csharp
class MyResourceManager<TInfo, TResource> : AResourceManager<TInfo, TResource>
{
    ...

    private MyContentManager contentManager;

    protected override TResource Load(Info info) => contentManager.Read<TResource>(info.ContentName);

    public void Reload()
    {
        foreach (var resource in Resources)
        {
            contentManager.Reload(pair.Key, pair.Value);
        }
    }
}
```

**Comment by Doraku** [comment]
Just added a `Resources` property, keep in mind that calling it will allocate the array containing all the resources (it uses the lock to make a safe copy of what is inside the manager) :)

**Comment by jnoyola** [comment]
Thanks! I can work with that. My use case at least should be rare enough that the memory allocation isn't an issue. I look forward to the next nuget version.
