### ISSUE TITLE
List All Components

### ISSUE THREAD

**Issue by generatives** [Doraku/DefaultEcs#95]
I want to write a simple inspector/editor for my game engine using DefaultECS. I'd like to be able to enumerate all the components attached to an Entity and use reflection to provide editors for there properties. Is there a good way of doing this?

**Comment by Doraku** [comment]
Sure you could use the [Entity.ReadAllComponents](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/DefaultEcs-Entity-ReadAllComponents(DefaultEcs-Serialization-IComponentReader).md) method or if you want to be able to react to your component changes, you can use the [World.SubscriveComponentAdded/Changed/Removed](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/DefaultEcs-World-SubscribeComponentAdded-T-(DefaultEcs-ComponentAddedHandler-T-).md), although you will need to make subscriptions for all your possible component types.

**Comment by generatives** [comment]
I will look into the Entity.ReadAllComponents method, I initially dismissed it since it seemed to be built for serialization. What I ended up doing was keeping a list of all possible component types (I added an attribute to each one and find all the classes/structs with the attribute). I made my component editor code generic and called it using reflection for each possible component type. The code includes a call to Entity.Has<T>() and only creates the editor if the entity has the type.

**Comment by generatives** [comment]
[https://github.com/generatives/Wrecker/blob/edcf7dd0aeab0a2749c1a2ba15186cb21aab9943/Clunker/Editor/Inspector/Inspector.cs](Link to the code) if anyone is interested.

**Comment by Doraku** [comment]
> I initially dismissed it since it seemed to be built for serialization.

It is but since it is just a simple interface to implement, your `Inspector ` could even implement it itself. Also it should remove the need for you to use reflection to call your generic method, not that performance is that important in an editor I guess.

**Comment by generatives** [comment]
I see in the source that Entity.ReadAllComponents works by publishing a message to the World instance. Is the message processed synchronously?

**Comment by Doraku** [comment]
Yep, partly to keep a simple implementation and not create memory pressure automatically, mostly because I am lazy, every message is synchronous.

**Comment by generatives** [comment]
Okay, thank you
