### ISSUE TITLE
Disposable Components

### ISSUE THREAD

**Issue by jnoyola** [Doraku/DefaultEcs#99]
It looks like there's no built-in support for simple disposable components, is that right? I just want to make sure before I do something manual. You can subscribe to various messages, but the `WorldDisposedMessage` doesn't trigger `EntityDisposedMessage`, and that doesn't trigger a `ComponentRemovedMessage`, is that right?

It looks like options are:
* Use `AResourceManager` to dispose the resource, which seems overkill for a disposable component that you don't need cached and/or doesn't get loaded.
* Subscribe to all 3 disposal messages so you can dispose regardless of how it's torn down.
* Track it manually.

My use case is for a `BufferPool` from BepuPhysics, where creating one is as simple as `new BufferPool()` but I have to make sure to `Dispose()` it.

**Comment by Doraku** [comment]
Actually subscribing to [ComponentRemoved](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/DefaultEcs-World-SubscribeComponentRemoved-T-(DefaultEcs-ComponentRemovedHandler-T-).md) will be called on an entity disposed and a world disposed if there is a component remaining. AResourceManager use this mechanism internally (https://github.com/Doraku/DefaultEcs/blob/master/source/DefaultEcs/Resource/AResourceManager.cs#L272). The messages types are internal so you can't really subscribe on them anyway.

**Comment by jnoyola** [comment]
> Actually subscribing to ComponentRemoved will be called on an entity disposed and a world disposed if there is a component remaining.

Oh, great! I guess I got lost in the weeds and missed it.

> I didn't put any logic for disposable component because I thought some people would want to handle the life cycle of their disposables themselves but the `World.SuscribeComponentRemoved` should help you achieve this behavior without too much hassle.

Fair enough, I'll use that. Thanks!
